<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="cm" nsURI="http://de.ubt.ai1.bw.qvt.examples.cm.ecore" nsPrefix="cm">
  <eClassifiers xsi:type="ecore:EClass" name="Student" eSuperTypes="#//Person">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="studentNo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lectures" upperBound="-1"
        eType="#//Lecture"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Teacher" eSuperTypes="#//Person">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="staffId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lectures" upperBound="-1"
        eType="#//Lecture" eOpposite="#//Lecture/teacher"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrganizationalEntity" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Person" abstract="true" eSuperTypes="#//OrganizationalEntity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="birthday" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="placeOfBirth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstNames" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrganizationalUnit" eSuperTypes="#//OrganizationalEntity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containedEntities" upperBound="-1"
        eType="#//OrganizationalEntity" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Examination">
    <eStructuralFeatures xsi:type="ecore:EReference" name="containingSemester" eType="#//Semester"
        eOpposite="#//Semester/containedExaminations"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="grade" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="teacher" eType="#//Teacher"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lecture" eType="#//Lecture"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="student" eType="#//Student"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Lecture">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lectureNo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredByLectures" upperBound="-1"
        eType="#//Lecture" eOpposite="#//Lecture/requiredLectures"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredLectures" upperBound="-1"
        eType="#//Lecture" eOpposite="#//Lecture/requiredByLectures"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="teacher" eType="#//Teacher"
        eOpposite="#//Teacher/lectures"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="module" eType="#//Module"
        eOpposite="#//Module/lecture"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Semester">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="year" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="winter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containedExaminations"
        upperBound="-1" eType="#//Examination" containment="true" eOpposite="#//Examination/containingSemester"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Module">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lecture" eType="#//Lecture"
        eOpposite="#//Lecture/module"/>
  </eClassifiers>
</ecore:EPackage>
