package de.tbuchmann.bxagent.bags2bags;

// EMF imports for source and target packages
import bags1.*;
import bags2.*;
import org.eclipse.emf.ecore.*;
import org.eclipse.emf.ecore.resource.*;
import org.eclipse.emf.ecore.xmi.XMIResource;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.common.util.EList;
import java.util.*;
import dev.emtagent.correspondence.CorrespondenceModel;
import dev.emtagent.correspondence.TransformationContext;
import dev.emtagent.correspondence.SyncConflictPolicy;
import dev.emtagent.correspondence.SyncConflict;
import dev.emtagent.correspondence.SyncResult;

/**
 * Bidirectional EMF transformation: bags1 ↔ bags2
 * Generated by emt-agent.
 *
 * WARNING: Do not edit manually - will be overwritten on regeneration.
 */
public class Bags12Bags2Transformation {

    // ════════════════════════════════════════════════════════════════════════
    // Transformation Options
    // ════════════════════════════════════════════════════════════════════════

    /**
     * Configuration options for non-deterministic transformation steps.
     * Includes both attribute-level options and structural backward-direction parameters.
     * Pass to transform() or transformBack() to control ambiguous mappings.
     */
    public record Options(
    ) {
        /** Default options. */
        public static Options defaults() {
            return new Options(
            );
        }
    }

    // ════════════════════════════════════════════════════════════════════════
    // Post-Processor Hook
    // ════════════════════════════════════════════════════════════════════════

    /**
     * Optional post-processing hook for derived structure that cannot be expressed
     * as attribute or reference mappings (e.g. building a linked list from containment order).
     * Pass to any transform() or transformBack() overload.
     */
    public interface PostProcessor {
        /**
         * Called before target objects are deleted (incremental mode only, CASCADE policy).
         * Use to repair derived relationships (e.g. re-link neighbors in a linked list)
         * while the objects are still reachable in the model.
         */
        default void beforeDeletions(List<EObject> targetObjectsToDelete) {}

        /**
         * Called after all phases of the transformation complete (batch and incremental).
         *
         * @param readFrom  the resource that was read (source model in forward, target model in backward)
         * @param writeTo   the resource that was written (target model in forward, source model in backward)
         * @param objectMap correspondence map: readFrom object → writeTo object
         * @param created   newly created writeTo objects (in batch mode: all non-root objects)
         * @param updated   attribute-updated writeTo objects (empty in batch mode)
         */
        default void afterTransform(Resource readFrom, Resource writeTo,
                                     Map<EObject, EObject> objectMap,
                                     List<EObject> created,
                                     List<EObject> updated) {}

        /** No-op implementation used by all overloads that do not supply a PostProcessor. */
        PostProcessor NOOP = new PostProcessor() {};
    }

    // ════════════════════════════════════════════════════════════════════════
    // Public Entry Points — Forward
    // ════════════════════════════════════════════════════════════════════════

    /**
     * Transforms the contents of sourceResource into targetResource using default options.
     * Both resources must already exist and root elements must be pre-created.
     */
    public static void transform(Resource sourceResource, Resource targetResource) {
        transform(sourceResource, targetResource, Options.defaults(), PostProcessor.NOOP);
    }

    /** Batch transform with post-processing hook. */
    public static void transform(Resource sourceResource, Resource targetResource, PostProcessor postProcessor) {
        transform(sourceResource, targetResource, Options.defaults(), postProcessor);
    }

    /**
     * Transforms the contents of sourceResource into targetResource.
     * Both resources must already exist and root elements must be pre-created.
     * After a successful batch transformation a correspondence model is created automatically.
     */
    public static void transform(Resource sourceResource, Resource targetResource, Options options) {
        transform(sourceResource, targetResource, options, PostProcessor.NOOP);
    }

    /** Batch transform with options and post-processing hook. */
    public static void transform(Resource sourceResource, Resource targetResource, Options options, PostProcessor postProcessor) {
        if (sourceResource == null || targetResource == null) {
            return;
        }
        TransformationContext ctx = TransformationContext.builder()
                .sourceModel(sourceResource)
                .existingTarget(targetResource)
                .direction(TransformationContext.Direction.SOURCE_TO_TARGET)
                .build();
        transform(ctx, options, postProcessor);
    }

    /**
     * Incrementally transforms sourceResource into targetResource using the supplied correspondence model.
     * The correspondence model must have been created by a previous batch transformation.
     */
    public static void transform(Resource sourceResource, Resource targetResource, Resource corrResource) {
        transform(sourceResource, targetResource, corrResource, Options.defaults(), PostProcessor.NOOP);
    }

    /** Incremental transform with post-processing hook. */
    public static void transform(Resource sourceResource, Resource targetResource, Resource corrResource, PostProcessor postProcessor) {
        transform(sourceResource, targetResource, corrResource, Options.defaults(), postProcessor);
    }

    /**
     * Incrementally transforms sourceResource into targetResource using the supplied correspondence model.
     * The correspondence model must have been created by a previous batch transformation.
     */
    public static void transform(Resource sourceResource, Resource targetResource, Resource corrResource, Options options) {
        transform(sourceResource, targetResource, corrResource, options, PostProcessor.NOOP);
    }

    /** Incremental transform with options and post-processing hook. */
    public static void transform(Resource sourceResource, Resource targetResource, Resource corrResource, Options options, PostProcessor postProcessor) {
        transform(sourceResource, targetResource, corrResource, TransformationContext.DeletionPolicy.TOMBSTONE, options, postProcessor);
    }

    /** Incremental transform with explicit deletion policy. */
    public static void transform(Resource sourceResource, Resource targetResource, Resource corrResource, TransformationContext.DeletionPolicy deletionPolicy) {
        transform(sourceResource, targetResource, corrResource, deletionPolicy, Options.defaults(), PostProcessor.NOOP);
    }

    /** Incremental transform with explicit deletion policy and post-processing hook. */
    public static void transform(Resource sourceResource, Resource targetResource, Resource corrResource, TransformationContext.DeletionPolicy deletionPolicy, PostProcessor postProcessor) {
        transform(sourceResource, targetResource, corrResource, deletionPolicy, Options.defaults(), postProcessor);
    }

    /** Incremental transform with explicit deletion policy and options. */
    public static void transform(Resource sourceResource, Resource targetResource, Resource corrResource, TransformationContext.DeletionPolicy deletionPolicy, Options options) {
        transform(sourceResource, targetResource, corrResource, deletionPolicy, options, PostProcessor.NOOP);
    }

    /** Incremental transform with explicit deletion policy, options and post-processing hook. */
    public static void transform(Resource sourceResource, Resource targetResource, Resource corrResource, TransformationContext.DeletionPolicy deletionPolicy, Options options, PostProcessor postProcessor) {
        if (sourceResource == null || targetResource == null || corrResource == null) {
            return;
        }
        TransformationContext ctx = TransformationContext.builder()
                .sourceModel(sourceResource)
                .existingTarget(targetResource)
                .corrModel(corrResource)
                .direction(TransformationContext.Direction.SOURCE_TO_TARGET)
                .deletionPolicy(deletionPolicy)
                .build();
        transform(ctx, options, postProcessor);
    }

    /** Incremental-aware transform using default options. */
    public static void transform(TransformationContext ctx) {
        transform(ctx, Options.defaults(), PostProcessor.NOOP);
    }

    /** Incremental-aware transform. Dispatches to batch or incremental path based on ctx. */
    public static void transform(TransformationContext ctx, Options options) {
        transform(ctx, options, PostProcessor.NOOP);
    }

    /** Incremental-aware transform with post-processing hook. */
    public static void transform(TransformationContext ctx, PostProcessor postProcessor) {
        transform(ctx, Options.defaults(), postProcessor);
    }

    /** Incremental-aware transform with options and post-processing hook. */
    public static void transform(TransformationContext ctx, Options options, PostProcessor postProcessor) {
        if (ctx.isIncremental()) {
            transformIncremental(ctx, options, postProcessor);
        } else {
            transformBatch(ctx, options, postProcessor);
        }
    }

    // ════════════════════════════════════════════════════════════════════════
    // Public Entry Points — Backward
    // ════════════════════════════════════════════════════════════════════════

    /**
     * Transforms the contents of targetResource back into sourceResource using default options.
     */
    public static void transformBack(Resource targetResource, Resource sourceResource) {
        transformBack(targetResource, sourceResource, Options.defaults(), PostProcessor.NOOP);
    }

    /** Batch backward transform with post-processing hook. */
    public static void transformBack(Resource targetResource, Resource sourceResource, PostProcessor postProcessor) {
        transformBack(targetResource, sourceResource, Options.defaults(), postProcessor);
    }

    /**
     * Transforms the contents of targetResource back into sourceResource.
     */
    public static void transformBack(Resource targetResource, Resource sourceResource, Options options) {
        transformBack(targetResource, sourceResource, options, PostProcessor.NOOP);
    }

    /** Batch backward transform with options and post-processing hook. */
    public static void transformBack(Resource targetResource, Resource sourceResource, Options options, PostProcessor postProcessor) {
        if (targetResource == null || sourceResource == null) {
            return;
        }
        TransformationContext ctx = TransformationContext.builder()
                .sourceModel(targetResource)
                .existingTarget(sourceResource)
                .direction(TransformationContext.Direction.TARGET_TO_SOURCE)
                .build();
        transformBack(ctx, options, postProcessor);
    }

    /**
     * Incrementally transforms targetResource back into sourceResource using the supplied correspondence model.
     * The correspondence model must have been created by a previous batch transformation.
     */
    public static void transformBack(Resource targetResource, Resource sourceResource, Resource corrResource) {
        transformBack(targetResource, sourceResource, corrResource, Options.defaults(), PostProcessor.NOOP);
    }

    /** Incremental backward transform with post-processing hook. */
    public static void transformBack(Resource targetResource, Resource sourceResource, Resource corrResource, PostProcessor postProcessor) {
        transformBack(targetResource, sourceResource, corrResource, Options.defaults(), postProcessor);
    }

    /**
     * Incrementally transforms targetResource back into sourceResource using the supplied correspondence model.
     * The correspondence model must have been created by a previous batch transformation.
     */
    public static void transformBack(Resource targetResource, Resource sourceResource, Resource corrResource, Options options) {
        transformBack(targetResource, sourceResource, corrResource, options, PostProcessor.NOOP);
    }

    /** Incremental backward transform with options and post-processing hook. */
    public static void transformBack(Resource targetResource, Resource sourceResource, Resource corrResource, Options options, PostProcessor postProcessor) {
        transformBack(targetResource, sourceResource, corrResource, TransformationContext.DeletionPolicy.TOMBSTONE, options, postProcessor);
    }

    /** Incremental backward transform with explicit deletion policy. */
    public static void transformBack(Resource targetResource, Resource sourceResource, Resource corrResource, TransformationContext.DeletionPolicy deletionPolicy) {
        transformBack(targetResource, sourceResource, corrResource, deletionPolicy, Options.defaults(), PostProcessor.NOOP);
    }

    /** Incremental backward transform with explicit deletion policy and post-processing hook. */
    public static void transformBack(Resource targetResource, Resource sourceResource, Resource corrResource, TransformationContext.DeletionPolicy deletionPolicy, PostProcessor postProcessor) {
        transformBack(targetResource, sourceResource, corrResource, deletionPolicy, Options.defaults(), postProcessor);
    }

    /** Incremental backward transform with explicit deletion policy and options. */
    public static void transformBack(Resource targetResource, Resource sourceResource, Resource corrResource, TransformationContext.DeletionPolicy deletionPolicy, Options options) {
        transformBack(targetResource, sourceResource, corrResource, deletionPolicy, options, PostProcessor.NOOP);
    }

    /** Incremental backward transform with explicit deletion policy, options and post-processing hook. */
    public static void transformBack(Resource targetResource, Resource sourceResource, Resource corrResource, TransformationContext.DeletionPolicy deletionPolicy, Options options, PostProcessor postProcessor) {
        if (targetResource == null || sourceResource == null || corrResource == null) {
            return;
        }
        TransformationContext ctx = TransformationContext.builder()
                .sourceModel(targetResource)
                .existingTarget(sourceResource)
                .corrModel(corrResource)
                .direction(TransformationContext.Direction.TARGET_TO_SOURCE)
                .deletionPolicy(deletionPolicy)
                .build();
        transformBack(ctx, options, postProcessor);
    }

    /** Incremental-aware backward transform using default options. */
    public static void transformBack(TransformationContext ctx) {
        transformBack(ctx, Options.defaults(), PostProcessor.NOOP);
    }

    /** Incremental-aware backward transform. */
    public static void transformBack(TransformationContext ctx, Options options) {
        transformBack(ctx, options, PostProcessor.NOOP);
    }

    /** Incremental-aware backward transform with post-processing hook. */
    public static void transformBack(TransformationContext ctx, PostProcessor postProcessor) {
        transformBack(ctx, Options.defaults(), postProcessor);
    }

    /** Incremental-aware backward transform with options and post-processing hook. */
    public static void transformBack(TransformationContext ctx, Options options, PostProcessor postProcessor) {
        if (ctx.isIncremental()) {
            transformIncrementalBack(ctx, options, postProcessor);
        } else {
            transformBatchBack(ctx, options, postProcessor);
        }
    }

    // ════════════════════════════════════════════════════════════════════════
    // Batch Forward Path
    // ════════════════════════════════════════════════════════════════════════

    private static void transformBatch(TransformationContext ctx, Options options, PostProcessor postProcessor) {
        Resource sourceResource = ctx.getSourceModel();
        Resource targetResource = ctx.getExistingTarget();

        Map<EObject, EObject> objectMap = new HashMap<>();
        Set<EObject> visited = new HashSet<>();

        // Pre-populate objectMap with existing root element pairs (by index)
        // and apply root-type attribute mappings
        List<EObject> sourceRoots = sourceResource.getContents();
        List<EObject> targetRoots = targetResource.getContents();
        for (int i = 0; i < Math.min(sourceRoots.size(), targetRoots.size()); i++) {
            bags1.MyBag source = (bags1.MyBag) sourceRoots.get(i);
            bags2.MyBag target = (bags2.MyBag) targetRoots.get(i);
            objectMap.put(source, target);
        }

        // Phase 1: Traverse containment hierarchy and create contained objects
        for (EObject sourceRoot : sourceRoots) {
            createAndMapObjects(sourceRoot, objectMap, visited, options);
        }

        // Phase 1d: Aggregation (many source objects → one target object per group key)
        Map<EObject, EObject> _aggObjectMap = new java.util.LinkedHashMap<>();
        for (EObject _srcObj : allSourceObjects(sourceResource)) {
            if (_srcObj instanceof bags1.MyBag _srcContainer) {
                EObject _tgtObj = objectMap.get(_srcObj);
                if (_tgtObj instanceof bags2.MyBag _tgtContainer) {
                    materializeAggregationElement(_srcContainer, _tgtContainer, _aggObjectMap);
                }
            }
        }

        // Phase 2: Resolve all cross-references
        resolveReferences(objectMap);

        // After batch: create correspondence model (if resources have persistent URIs)
        if (sourceResource.getURI() != null && targetResource.getURI() != null
                && sourceResource.getResourceSet() != null) {
            org.eclipse.emf.common.util.URI corrURI = CorrespondenceModel.deriveCorrespondenceURI(
                    sourceResource.getURI(), targetResource.getURI());
            Resource corrResource = CorrespondenceModel.loadOrCreate(corrURI, sourceResource.getResourceSet());
            // Batch always rebuilds the correspondence from scratch — clear stale entries first.
            corrResource.getContents().clear();
            for (Map.Entry<EObject, EObject> entry : objectMap.entrySet()) {
                String _srcCR = entry.getKey().eContainmentFeature() != null ? entry.getKey().eContainmentFeature().getName() : "";
                String _tgtCR = entry.getValue().eContainmentFeature() != null ? entry.getValue().eContainmentFeature().getName() : "";
                CorrespondenceModel.addEntry(corrResource,
                        entry.getKey(), entry.getKey().eClass().getName(),
                        computeFingerprint(entry.getKey()),
                        entry.getValue(), entry.getValue().eClass().getName(),
                        computeFingerprintBack(entry.getValue()),
                        _srcCR, _tgtCR);
            }
            for (Map.Entry<EObject, EObject> entry : _aggObjectMap.entrySet()) {
                CorrespondenceModel.addAggregationEntry(corrResource,
                        entry.getKey(), entry.getKey().eClass().getName(),
                        computeFingerprint(entry.getKey()),
                        entry.getValue(), entry.getValue().eClass().getName(),
                        computeFingerprintBack(entry.getValue()));
            }
            CorrespondenceModel.saveAndUpdateTimestamp(corrResource);
        }

        // Post-processing: all non-root target objects are "created" in batch mode
        List<EObject> _batchCreated = new ArrayList<>(objectMap.values());
        java.util.Set<EObject> _aggCreatedSet = new java.util.LinkedHashSet<>(_aggObjectMap.values());
        _batchCreated.addAll(_aggCreatedSet);
        targetRoots.forEach(_batchCreated::remove);
        postProcessor.afterTransform(sourceResource, targetResource, objectMap, _batchCreated, List.of());
    }

    // ════════════════════════════════════════════════════════════════════════
    // Incremental Forward Path
    // ════════════════════════════════════════════════════════════════════════

    private static void transformIncremental(TransformationContext ctx, Options options, PostProcessor postProcessor) {
        Resource sourceModel   = ctx.getSourceModel();
        Resource existingTarget = ctx.getExistingTarget();
        Resource corrResource  = ctx.getCorrModel();
        com.google.common.collect.BiMap<EObject, EObject> corrIndex = ctx.getCorrIndex();
        List<EObject> _created = new ArrayList<>();
        List<EObject> _updated = new ArrayList<>();

        // Bootstrap: ensure root element pairs are in the corr model before Phase 1.
        // Without this, root elements (eContainer == null) would be treated as new objects
        // on the first incremental call and a duplicate root would be added to the target resource.
        {
            List<EObject> _sRoots = sourceModel.getContents();
            List<EObject> _tRoots = existingTarget.getContents();
            for (int _ri = 0; _ri < Math.min(_sRoots.size(), _tRoots.size()); _ri++) {
                EObject _sRoot = _sRoots.get(_ri);
                EObject _tRoot = _tRoots.get(_ri);
                if (CorrespondenceModel.findBySource(corrResource, _sRoot).isEmpty()) {
                    updateTargetAttributes(_sRoot, _tRoot, options);
                    String _rfp  = computeFingerprint(_sRoot);
                    String _rbfp = computeFingerprintBack(_tRoot);
                    CorrespondenceModel.addEntry(corrResource,
                            _sRoot, _sRoot.eClass().getName(), _rfp,
                            _tRoot, _tRoot.eClass().getName(), _rbfp, "", "");
                    corrIndex.put(_sRoot, _tRoot);
                }
            }
        }

        // Phase 1: Regular typed objects (TypeMappings only).
        // Role-based source types (e.g. FamilyMember) are handled exclusively in Phase 1b
        // to avoid consuming their change signal before mapRoleBasedTypesIncremental runs.
        for (EObject srcObj : allSourceObjects(sourceModel)) {
            if (!isCoveredByTypeMappingSource(srcObj)) continue;
            String currentFp = computeFingerprint(srcObj);
            Optional<EObject> existingEntry = CorrespondenceModel.findBySource(corrResource, srcObj);

            if (existingEntry.isEmpty()) {
                // New object: create and add to target containment
                EObject newTarget = createNewTargetObject(srcObj, options);
                if (newTarget != null) {
                    addToTargetContainment(srcObj, newTarget, existingTarget, corrIndex);
                    String _srcCR = srcObj.eContainmentFeature() != null ? srcObj.eContainmentFeature().getName() : "";
                    String _tgtCR = newTarget.eContainmentFeature() != null ? newTarget.eContainmentFeature().getName() : "";
                    CorrespondenceModel.addEntry(corrResource,
                            srcObj, srcObj.eClass().getName(), currentFp,
                            newTarget, newTarget.eClass().getName(), computeFingerprintBack(newTarget), _srcCR, _tgtCR);
                    corrIndex.put(srcObj, newTarget);
                    _created.add(newTarget);
                }
            } else {
                // Known: check containment role and fingerprint for changes
                EObject targetObj = corrIndex.get(srcObj);
                // Re-attach to target resource if detached (e.g. target was reset but corr model persists).
                // Adding a root re-attaches all its contained children transitively.
                if (targetObj != null && targetObj.eResource() == null) {
                    addToTargetContainment(srcObj, targetObj, existingTarget, corrIndex);
                }
                String _currentSrcRole = srcObj.eContainmentFeature() != null ? srcObj.eContainmentFeature().getName() : "";
                String _storedSrcRole  = CorrespondenceModel.getSourceContainmentRole(existingEntry.get());
                if (_storedSrcRole == null) _storedSrcRole = "";
                if (!_currentSrcRole.equals(_storedSrcRole)) {
                    // Containment role changed for a TypeMapping object.
                    // Update the stored role; for role-based types this is handled in Phase 1b.
                    CorrespondenceModel.updateSourceContainmentRole(existingEntry.get(), _currentSrcRole);
                }
                String storedFp = CorrespondenceModel.getFingerprint(existingEntry.get());
                if (!currentFp.equals(storedFp)) {
                    if (targetObj != null) {
                        updateTargetAttributes(srcObj, targetObj, options);
                        CorrespondenceModel.updateFingerprint(existingEntry.get(), currentFp);
                        // Also update target fingerprint so backward direction sees a consistent baseline.
                        CorrespondenceModel.updateTargetFingerprint(existingEntry.get(), computeFingerprintBack(targetObj));
                        _updated.add(targetObj);
                    }
                }
            }
        }

        // Phase 1d: Aggregation (incremental)
        java.util.Map<EObject, EObject> _aggregationIndex = CorrespondenceModel.buildAggregationIndex(corrResource);
        materializeAggregationElementIncremental(sourceModel, existingTarget, corrResource, corrIndex, _aggregationIndex, _created, _updated);

        // Phase 2: Detect and handle deleted source objects
        // EMF nullifies CE_SOURCE_OBJECT when the object is deleted from the resource,
        // so we scan for entries with null sourceObject rather than comparing allSourceObjects with corrIndex.
        List<EObject> _deletedFwdEntries = new ArrayList<>(CorrespondenceModel.findDeletedSourceEntries(corrResource));
        // Notify post-processor before actual deletion (CASCADE only) so derived structure can be repaired first
        if (ctx.getDeletionPolicy() == TransformationContext.DeletionPolicy.CASCADE) {
            List<EObject> _toDelete = new ArrayList<>();
            for (EObject _corrEntry : _deletedFwdEntries) {
                EObject targetObj = CorrespondenceModel.getTargetObject(_corrEntry);
                if (targetObj != null) _toDelete.add(targetObj);
            }
            postProcessor.beforeDeletions(_toDelete);
        }
        for (EObject _corrEntry : _deletedFwdEntries) {
            EObject targetObj = CorrespondenceModel.getTargetObject(_corrEntry);
            switch (ctx.getDeletionPolicy()) {
                case CASCADE -> {
                    if (targetObj != null) {
                        EcoreUtil.delete(targetObj, true);
                    }
                    CorrespondenceModel.removeCorrespondenceEntry(corrResource, _corrEntry);
                }
                case ORPHAN -> CorrespondenceModel.removeCorrespondenceEntry(corrResource, _corrEntry);
                case TOMBSTONE -> CorrespondenceModel.markOrphaned(_corrEntry);
            }
        }

        // Phase 3: Resolve cross-references incrementally using corrIndex as lookup.
        // Must run after Phase 1 so all new objects are in corrIndex.
        // Iterates all source objects (not just changed ones) because cross-reference changes
        // are not captured by the fingerprint.
        resolveReferencesIncremental(sourceModel, existingTarget, corrIndex);

        CorrespondenceModel.saveAndUpdateTimestamp(corrResource);

        postProcessor.afterTransform(sourceModel, existingTarget, corrIndex, _created, _updated);
    }

    // ════════════════════════════════════════════════════════════════════════
    // Batch Backward Path
    // ════════════════════════════════════════════════════════════════════════

    private static void transformBatchBack(TransformationContext ctx, Options options, PostProcessor postProcessor) {
        // In backward direction: ctx.getSourceModel() = target model (read from)
        //                        ctx.getExistingTarget() = source model (written to)
        Resource targetResource = ctx.getSourceModel();
        Resource sourceResource = ctx.getExistingTarget();

        Map<EObject, EObject> objectMap = new HashMap<>();
        Set<EObject> visited = new HashSet<>();

        // Pre-populate objectMap with existing root element pairs (by index)
        // and apply root-type backward attribute mappings
        List<EObject> targetRoots = targetResource.getContents();
        List<EObject> sourceRoots = sourceResource.getContents();
        for (int i = 0; i < Math.min(targetRoots.size(), sourceRoots.size()); i++) {
            bags2.MyBag target = (bags2.MyBag) targetRoots.get(i);
            bags1.MyBag source = (bags1.MyBag) sourceRoots.get(i);
            objectMap.put(target, source);
        }

        // Phase 1: Traverse containment hierarchy and create contained objects
        for (EObject targetRoot : targetRoots) {
            createAndMapObjectsBack(targetRoot, objectMap, visited, options);
        }

        // Phase 1d: Aggregation backward (batch)
        Map<EObject, EObject> _aggBackObjectMap = new java.util.LinkedHashMap<>();
        for (EObject _tgtObj : allSourceObjects(targetResource)) {
            if (_tgtObj instanceof bags2.MyBag _tgtContainer) {
                EObject _srcObj = objectMap.get(_tgtObj);
                if (_srcObj instanceof bags1.MyBag _srcContainer) {
                    materializeAggregationBackElement(_tgtContainer, _srcContainer, _aggBackObjectMap);
                }
            }
        }

        // Phase 2: Resolve all cross-references
        resolveReferencesBack(objectMap);

        // Post-processing: all non-root source objects are "created" in batch backward mode
        List<EObject> _batchBackCreated = new ArrayList<>(objectMap.values());
        java.util.Set<EObject> _aggBackCreatedSet = new java.util.LinkedHashSet<>(_aggBackObjectMap.values());
        _batchBackCreated.addAll(_aggBackCreatedSet);
        sourceRoots.forEach(_batchBackCreated::remove);
        postProcessor.afterTransform(targetResource, sourceResource, objectMap, _batchBackCreated, List.of());
    }

    // ════════════════════════════════════════════════════════════════════════
    // Incremental Backward Path
    // ════════════════════════════════════════════════════════════════════════

    private static void transformIncrementalBack(TransformationContext ctx, Options options, PostProcessor postProcessor) {
        // In backward direction:
        // ctx.getSourceModel()    = target model (what we read from, in forward naming = "target")
        // ctx.getExistingTarget() = source model (what we write to, in forward naming = "source")
        Resource targetModel  = ctx.getSourceModel();
        Resource sourceModel  = ctx.getExistingTarget();
        Resource corrResource = ctx.getCorrModel();
        // corrIndex is forward: source→target.  corrIndex.inverse() is target→source.
        com.google.common.collect.BiMap<EObject, EObject> corrIndex = ctx.getCorrIndex();
        List<EObject> _createdBack = new ArrayList<>();
        List<EObject> _updatedBack = new ArrayList<>();

        // Bootstrap: ensure root element pairs are in the corr model before Phase 1.
        {
            List<EObject> _tRoots = targetModel.getContents();
            List<EObject> _sRoots = sourceModel.getContents();
            for (int _ri = 0; _ri < Math.min(_tRoots.size(), _sRoots.size()); _ri++) {
                EObject _tRoot = _tRoots.get(_ri);
                EObject _sRoot = _sRoots.get(_ri);
                if (!corrIndex.inverse().containsKey(_tRoot)) {
                    updateSourceAttributes(_tRoot, _sRoot, options);
                    String _rfp  = computeFingerprint(_sRoot);
                    String _rbfp = computeFingerprintBack(_tRoot);
                    CorrespondenceModel.addEntry(corrResource,
                            _sRoot, _sRoot.eClass().getName(), _rfp,
                            _tRoot, _tRoot.eClass().getName(), _rbfp, "", "");
                    corrIndex.put(_sRoot, _tRoot);
                }
            }
        }

        // Phase 1: All typed objects — TypeMappings AND role-based target types.
        // For TypeMapping objects: update attributes + fingerprint here.
        // For role-based objects (e.g. Male/Female): update simple attributes here but
        //   do NOT update the fingerprint — Phase 1b (mapRoleBasedTypesIncrementalBack)
        //   needs to see the mismatch to apply structural changes (e.g. family moves)
        //   before committing the new fingerprint.
        for (EObject tgtObj : allSourceObjects(targetModel)) {
            if (!corrIndex.inverse().containsKey(tgtObj)) {
                // New target object — only create if it's a TypeMapping type.
                // New role-based objects are handled in Phase 1b.
                if (!isCoveredByTypeMappingTarget(tgtObj)) continue;
                EObject newSource = createNewSourceObject(tgtObj, options);
                if (newSource != null) {
                    addToSourceContainment(tgtObj, newSource, sourceModel, corrIndex);
                    String srcFp = computeFingerprint(newSource);
                    String tgtFp = computeFingerprintBack(tgtObj);
                    String _srcCR = newSource.eContainmentFeature() != null ? newSource.eContainmentFeature().getName() : "";
                    String _tgtCR = tgtObj.eContainmentFeature() != null ? tgtObj.eContainmentFeature().getName() : "";
                    CorrespondenceModel.addEntry(corrResource,
                            newSource, newSource.eClass().getName(), srcFp,
                            tgtObj, tgtObj.eClass().getName(), tgtFp, _srcCR, _tgtCR);
                    corrIndex.put(newSource, tgtObj);
                    _createdBack.add(newSource);
                }
            } else {
                // Known: check containment role and target fingerprint for changes
                EObject srcObj = corrIndex.inverse().get(tgtObj);
                // Re-attach source to source resource if detached (e.g. source was reset but corr model persists).
                if (srcObj != null && srcObj.eResource() == null) {
                    addToSourceContainment(tgtObj, srcObj, sourceModel, corrIndex);
                }
                if (srcObj != null) {
                    Optional<EObject> entryOpt = CorrespondenceModel.findBySource(corrResource, srcObj);
                    if (entryOpt.isPresent()) {
                        String _currentTgtRole = tgtObj.eContainmentFeature() != null ? tgtObj.eContainmentFeature().getName() : "";
                        String _storedTgtRole  = CorrespondenceModel.getTargetContainmentRole(entryOpt.get());
                        if (_storedTgtRole == null) _storedTgtRole = "";
                        if (!_currentTgtRole.equals(_storedTgtRole)) {
                            // Target containment role changed for a TypeMapping object.
                            // Update stored role; for role-based types this is handled in Phase 1b.
                            CorrespondenceModel.updateTargetContainmentRole(entryOpt.get(), _currentTgtRole);
                        }
                        String storedFp = CorrespondenceModel.getTargetFingerprint(entryOpt.get());
                        String currentFp = computeFingerprintBack(tgtObj);
                        if (storedFp == null || storedFp.isEmpty() || !currentFp.equals(storedFp)) {
                            // Apply backward attribute mappings for this type
                            updateSourceAttributes(tgtObj, srcObj, options);
                            // Only commit the fingerprint for TypeMapping types.
                            // Role-based types: Phase 1b commits the fingerprint after structural updates.
                            if (isCoveredByTypeMappingTarget(tgtObj)) {
                                CorrespondenceModel.updateTargetFingerprint(entryOpt.get(), currentFp);
                                // Also update source fingerprint so forward direction sees a consistent baseline.
                                CorrespondenceModel.updateFingerprint(entryOpt.get(), computeFingerprint(srcObj));
                                _updatedBack.add(srcObj);
                            }
                        }
                    }
                }
            }
        }

        // Phase 1d: Aggregation backward (incremental)
        java.util.Map<EObject, EObject> _aggregationIndexBack = CorrespondenceModel.buildAggregationIndex(corrResource);
        materializeAggregationBackElementIncremental(targetModel, sourceModel, corrResource, corrIndex, _aggregationIndexBack, _createdBack, _updatedBack);

        // Phase 2: Detect and handle deleted target objects
        // EMF nullifies CE_TARGET_OBJECT when the object is deleted from the resource,
        // so we scan for entries with null targetObject rather than comparing allTargetObjects with corrIndex.
        List<EObject> _deletedBwdEntries = new ArrayList<>(CorrespondenceModel.findDeletedTargetEntries(corrResource));
        // Notify post-processor before actual deletion (CASCADE only)
        if (ctx.getDeletionPolicy() == TransformationContext.DeletionPolicy.CASCADE) {
            List<EObject> _toDeleteBack = new ArrayList<>();
            for (EObject _corrEntry : _deletedBwdEntries) {
                EObject srcObj = CorrespondenceModel.getSourceObject(_corrEntry);
                if (srcObj != null) _toDeleteBack.add(srcObj);
            }
            postProcessor.beforeDeletions(_toDeleteBack);
        }
        for (EObject _corrEntry : _deletedBwdEntries) {
            EObject srcObj = CorrespondenceModel.getSourceObject(_corrEntry);
            switch (ctx.getDeletionPolicy()) {
                case CASCADE -> {
                    if (srcObj != null) {
                        EcoreUtil.delete(srcObj, true);
                    }
                    CorrespondenceModel.removeCorrespondenceEntry(corrResource, _corrEntry);
                }
                case ORPHAN -> CorrespondenceModel.removeCorrespondenceEntry(corrResource, _corrEntry);
                case TOMBSTONE -> CorrespondenceModel.markOrphaned(_corrEntry);
            }
        }

        // Phase 3: Resolve cross-references incrementally (backward direction).
        resolveReferencesIncrementalBack(targetModel, sourceModel, corrIndex);

        CorrespondenceModel.saveAndUpdateTimestamp(corrResource);

        postProcessor.afterTransform(targetModel, sourceModel, corrIndex.inverse(), _createdBack, _updatedBack);
    }

    // ════════════════════════════════════════════════════════════════════════
    // Phase 1: Object Creation and Attribute Mapping (Forward)
    // ════════════════════════════════════════════════════════════════════════

    /**
     * Recursively creates target objects for source object tree (containments only).
     * Maps attributes and stores source→target mapping.
     * Pre-existing entries in objectMap (e.g. root elements) are traversed but not recreated.
     */
    private static EObject createAndMapObjects(EObject source, Map<EObject, EObject> objectMap, Set<EObject> visited, Options options) {
        if (source == null) {
            return null;
        }

        // Use visited set to prevent infinite loops (objectMap alone is not enough
        // since root elements are pre-seeded and must still be traversed)
        if (visited.contains(source)) {
            return objectMap.get(source);
        }
        visited.add(source);

        EObject target;
        if (objectMap.containsKey(source)) {
            // Pre-existing entry (e.g. root element) — use it, still traverse children
            target = objectMap.get(source);
        } else {
            target = null;

            // Handle MyBag → MyBag
            if (source instanceof bags1.MyBag) {
                target = transformMyBag((bags1.MyBag) source, options);
            }

            if (target != null) {
                objectMap.put(source, target);
            }
        }

        if (target != null) {

            // Recursively transform containment references
            // Cardinality (isMany) is resolved at runtime via EMF feature metadata,
            // avoiding reliance on potentially incorrect LLM-provided sourceIsMany/targetIsMany flags.
            // No containment references defined
        }

        return target;
    }

    // ════════════════════════════════════════════════════════════════════════
    // Phase 2: Cross-Reference Resolution (Forward)
    // ════════════════════════════════════════════════════════════════════════

    /**
     * Resolves all cross-references (non-containment) using the object map.
     */
    @SuppressWarnings("unchecked")
    private static void resolveReferences(Map<EObject, EObject> objectMap) {
        // No cross-references defined
    }

    // ════════════════════════════════════════════════════════════════════════
    // Phase 1: Object Creation and Attribute Mapping (Backward)
    // ════════════════════════════════════════════════════════════════════════

    /**
     * Recursively creates source objects for target object tree (containments only).
     * Maps attributes and stores target→source mapping.
     * Pre-existing entries in objectMap (e.g. root elements) are traversed but not recreated.
     */
    private static EObject createAndMapObjectsBack(EObject target, Map<EObject, EObject> objectMap, Set<EObject> visited, Options options) {
        if (target == null) {
            return null;
        }

        // Use visited set to prevent infinite loops (objectMap alone is not enough
        // since root elements are pre-seeded and must still be traversed)
        if (visited.contains(target)) {
            return objectMap.get(target);
        }
        visited.add(target);

        EObject source;
        if (objectMap.containsKey(target)) {
            // Pre-existing entry (e.g. root element) — use it, still traverse children
            source = objectMap.get(target);
        } else {
            source = null;

            // Handle MyBag → MyBag
            if (target instanceof bags2.MyBag _typed) {
                source = transformBackMyBagAsMyBag(_typed, options);
            }

            if (source != null) {
                objectMap.put(target, source);
            }
        }

        if (source != null) {

            // Recursively transform containment references
            // Cardinality resolved at runtime via EMF feature metadata.
            // No containment references defined
        }

        return source;
    }

    // ════════════════════════════════════════════════════════════════════════
    // Phase 2: Cross-Reference Resolution (Backward)
    // ════════════════════════════════════════════════════════════════════════

    /**
     * Resolves all cross-references (non-containment) using the object map.
     */
    @SuppressWarnings("unchecked")
    private static void resolveReferencesBack(Map<EObject, EObject> objectMap) {
        // No cross-references defined
    }

    // ════════════════════════════════════════════════════════════════════════
    // Phase 3: Incremental Cross-Reference Resolution
    // ════════════════════════════════════════════════════════════════════════

    /**
     * Resolves all cross-references (non-containment) incrementally.
     * Uses corrIndex as lookup (not objectMap which doesn't exist in incremental mode).
     * Iterates ALL source objects — cross-reference changes are not captured by fingerprint.
     * For isMany references: clears the target list before refilling.
     */
    @SuppressWarnings("unchecked")
    private static void resolveReferencesIncremental(
            Resource sourceModel,
            Resource existingTarget,
            com.google.common.collect.BiMap<EObject, EObject> corrIndex) {
        // No cross-references defined
    }

    /**
     * Resolves all cross-references (non-containment) incrementally in the backward direction.
     * Uses corrIndex.inverse() as lookup.
     * For isMany references: clears the source list before refilling.
     */
    @SuppressWarnings("unchecked")
    private static void resolveReferencesIncrementalBack(
            Resource targetModel,
            Resource sourceModel,
            com.google.common.collect.BiMap<EObject, EObject> corrIndex) {
        // No cross-references defined
    }

    // ════════════════════════════════════════════════════════════════════════
    // Phase 1c: Edge Materialization Methods
    // ════════════════════════════════════════════════════════════════════════


    // ════════════════════════════════════════════════════════════════════════
    // Helper Methods for Type-Specific Transformations
    // ════════════════════════════════════════════════════════════════════════

    /**
     * Transforms MyBag → MyBag
     */
    private static bags2.MyBag transformMyBag(bags1.MyBag source, Options options) {
        if (source == null) {
            return null;
        }

        bags2.MyBag target = Bags2Factory.eINSTANCE.createMyBag();

        return target;
    }

    /**
     * Transforms MyBag → MyBag (backward)
     */
    private static bags1.MyBag transformBackMyBagAsMyBag(bags2.MyBag target, Options options) {
        if (target == null) {
            return null;
        }

        bags1.MyBag source = Bags1Factory.eINSTANCE.createMyBag();

        return source;
    }


    // ════════════════════════════════════════════════════════════════════════
    // Incremental Helper Methods
    // ════════════════════════════════════════════════════════════════════════

    /**
     * Computes a fingerprint string for an EObject.
     * Uses sourceKeyAttributes from the TypeMapping when available; falls back to all attributes.
     */
    private static String computeFingerprint(EObject obj) {
        StringBuilder sb = new StringBuilder();
        sb.append(obj.eClass().getName()).append(":");
        if (obj instanceof bags1.MyBag typed) {
            for (EAttribute ea : obj.eClass().getEAllAttributes()) {
                if ("incrementalID".equals(ea.getName())) continue;
                sb.append(obj.eGet(ea)).append("|");
            }
            return sb.toString();
        }
        if (obj instanceof bags1.Element typed) {
            sb.append(typed.getValue()).append("|");
            // Non-key attributes for change detection
            for (EAttribute ea : obj.eClass().getEAllAttributes()) {
                if ("value".equals(ea.getName()) || "incrementalID".equals(ea.getName())) continue;
                sb.append(obj.eGet(ea)).append("|");
            }
            return sb.toString();
        }
        // Generic fallback: all attributes reflectively
        for (EAttribute ea : obj.eClass().getEAllAttributes()) {
            if ("incrementalID".equals(ea.getName())) continue;
            sb.append(obj.eGet(ea)).append("|");
        }
        return sb.toString();
    }

    /**
     * Finds an EObject in a resource by identifier (XMI-ID first, then URI fragment).
     */
    private static EObject findInModel(Resource resource, String identifier) {
        if (resource instanceof XMIResource xmi) {
            EObject obj = xmi.getEObject(identifier);
            if (obj != null) return obj;
        }
        try {
            return resource.getEObject(identifier);
        } catch (Exception e) {
            return null;
        }
    }

    /** Returns all EObjects in a resource as a flat list. */
    private static List<EObject> allSourceObjects(Resource resource) {
        List<EObject> all = new ArrayList<>();
        for (Iterator<EObject> it = resource.getAllContents(); it.hasNext(); ) {
            all.add(it.next());
        }
        return all;
    }

    // ── Aggregation: Element (bags1) → Element ──────────────────────────

    /**
     * Phase 1d forward (batch): groups sourceType instances by value,
     * creates one target Element per distinct value with multiplicity = group size.
     */
    private static void materializeAggregationElement(
            bags1.MyBag sourceParent,
            bags2.MyBag targetParent,
            Map<EObject, EObject> aggObjectMap) {
        java.util.Map<String, java.util.List<bags1.Element>> _groups = new java.util.LinkedHashMap<>();
        for (bags1.Element _srcElem : sourceParent.getElements()) {
            _groups.computeIfAbsent(_srcElem.getValue(), k -> new java.util.ArrayList<>()).add(_srcElem);
        }
        for (java.util.Map.Entry<String, java.util.List<bags1.Element>> _entry : _groups.entrySet()) {
            bags2.Element _tgtElem = Bags2Factory.eINSTANCE.createElement();
            _tgtElem.setValue(_entry.getKey());
            _tgtElem.setMultiplicity(_entry.getValue().size());
            targetParent.getElements().add(_tgtElem);
            for (bags1.Element _srcElem : _entry.getValue()) {
                aggObjectMap.put(_srcElem, _tgtElem);
            }
        }
    }

    /**
     * Phase 1d backward (batch): for each target Element, creates multiplicity many source
     * Elements with groupBySourceAttr set; leaves all other source attrs at defaults.
     */
    private static void materializeAggregationBackElement(
            bags2.MyBag targetParent,
            bags1.MyBag sourceParent,
            Map<EObject, EObject> aggObjectMap) {
        for (bags2.Element _tgtElem : targetParent.getElements()) {
            for (int _i = 0; _i < _tgtElem.getMultiplicity(); _i++) {
                bags1.Element _srcElem = Bags1Factory.eINSTANCE.createElement();
                _srcElem.setValue(_tgtElem.getValue());
                sourceParent.getElements().add(_srcElem);
                aggObjectMap.put(_srcElem, _tgtElem);
            }
        }
    }

    /**
     * Phase 1d forward (incremental): smart-sync aggregation groups.
     * Preserves existing target elements when the group key and count are unchanged.
     * Handles element additions, deletions, and value changes (group moves).
     */
    @SuppressWarnings("unchecked")
    private static void materializeAggregationElementIncremental(
            Resource sourceModel, Resource existingTarget,
            Resource corrResource,
            com.google.common.collect.BiMap<EObject, EObject> corrIndex,
            java.util.Map<EObject, EObject> aggregationIndex,
            List<EObject> _created, List<EObject> _updated) {

        // Step 1: build current groups, organized by (sourceParent, groupByValue)
        java.util.Map<bags1.MyBag,
                java.util.Map<String, java.util.List<bags1.Element>>> _groupsByParent
                = new java.util.LinkedHashMap<>();
        for (EObject _obj : allSourceObjects(sourceModel)) {
            if (_obj instanceof bags1.Element _srcElem
                    && _srcElem.eContainer() instanceof bags1.MyBag _srcBag) {
                _groupsByParent.computeIfAbsent(_srcBag, k -> new java.util.LinkedHashMap<>())
                    .computeIfAbsent(_srcElem.getValue(), k -> new java.util.ArrayList<>())
                    .add(_srcElem);
            }
        }

        // Step 2: index existing target elements by (targetParent, groupByValue)
        java.util.Map<bags2.MyBag,
                java.util.Map<String, bags2.Element>> _existingByParent
                = new java.util.LinkedHashMap<>();
        for (EObject _obj : allSourceObjects(existingTarget)) {
            if (_obj instanceof bags2.Element _tgtElem
                    && _tgtElem.eContainer() instanceof bags2.MyBag _tgtBag) {
                _existingByParent.computeIfAbsent(_tgtBag, k -> new java.util.LinkedHashMap<>())
                    .put(_tgtElem.getValue(), _tgtElem);
            }
        }

        // Step 3: process each current group
        java.util.Set<bags2.Element> _processedTargets = new java.util.HashSet<>();
        for (java.util.Map.Entry<bags1.MyBag,
                java.util.Map<String, java.util.List<bags1.Element>>> _parentEntry
                : _groupsByParent.entrySet()) {

            bags1.MyBag _srcBag = _parentEntry.getKey();
            EObject _tgtBagObj = corrIndex.get(_srcBag);
            if (!(_tgtBagObj instanceof bags2.MyBag _tgtBag)) continue;

            java.util.Map<String, bags2.Element> _existingInParent =
                _existingByParent.getOrDefault(_tgtBag, java.util.Collections.emptyMap());

            for (java.util.Map.Entry<String, java.util.List<bags1.Element>> _groupEntry
                    : _parentEntry.getValue().entrySet()) {
                String _value = _groupEntry.getKey();
                java.util.List<bags1.Element> _srcElems = _groupEntry.getValue();
                int _expectedCount = _srcElems.size();

                bags2.Element _tgtElem = _existingInParent.get(_value);
                if (_tgtElem != null) {
                    // Existing group: update multiplicity if changed
                    _processedTargets.add(_tgtElem);
                    if (_tgtElem.getMultiplicity() != _expectedCount) {
                        _tgtElem.setMultiplicity(_expectedCount);
                        String _newTgtFp = computeFingerprintBack(_tgtElem);
                        CorrespondenceModel.updateAllAggregationTargetFingerprints(corrResource, _tgtElem, _newTgtFp);
                        _updated.add(_tgtElem);
                    }
                    // Ensure all current source elements have correct corr entries
                    for (bags1.Element _srcElem : _srcElems) {
                        EObject _indexedTarget = aggregationIndex.get(_srcElem);
                        if (_indexedTarget == null) {
                            // New source element in existing group
                            String _srcFp = computeFingerprint(_srcElem);
                            String _tgtFp = computeFingerprintBack(_tgtElem);
                            CorrespondenceModel.addAggregationEntry(corrResource, _srcElem, "Element", _srcFp, _tgtElem, "Element", _tgtFp);
                            aggregationIndex.put(_srcElem, _tgtElem);
                        } else if (_indexedTarget != _tgtElem) {
                            // Source element moved from another group (value changed)
                            Optional<EObject> _oldCE = CorrespondenceModel.findBySource(corrResource, _srcElem);
                            _oldCE.ifPresent(ce -> {
                                CorrespondenceModel.updateTargetObject(ce, _tgtElem, "Element");
                                CorrespondenceModel.updateFingerprint(ce, computeFingerprint(_srcElem));
                                CorrespondenceModel.updateTargetFingerprint(ce, computeFingerprintBack(_tgtElem));
                            });
                            aggregationIndex.put(_srcElem, _tgtElem);
                        }
                        // else: already correctly indexed for this target
                    }
                } else {
                    // New group: create target element
                    bags2.Element _newTgt = Bags2Factory.eINSTANCE.createElement();
                    _newTgt.setValue(_value);
                    _newTgt.setMultiplicity(_expectedCount);
                    _tgtBag.getElements().add(_newTgt);
                    _processedTargets.add(_newTgt);
                    String _tgtFp = computeFingerprintBack(_newTgt);
                    for (bags1.Element _srcElem : _srcElems) {
                        EObject _indexedTarget = aggregationIndex.get(_srcElem);
                        if (_indexedTarget != null && _indexedTarget != _newTgt) {
                            // Element moved from another group
                            Optional<EObject> _oldCE = CorrespondenceModel.findBySource(corrResource, _srcElem);
                            _oldCE.ifPresent(ce -> {
                                CorrespondenceModel.updateTargetObject(ce, _newTgt, "Element");
                                CorrespondenceModel.updateFingerprint(ce, computeFingerprint(_srcElem));
                                CorrespondenceModel.updateTargetFingerprint(ce, computeFingerprintBack(_newTgt));
                            });
                        } else if (_indexedTarget == null) {
                            String _srcFp = computeFingerprint(_srcElem);
                            CorrespondenceModel.addAggregationEntry(corrResource, _srcElem, "Element", _srcFp, _newTgt, "Element", _tgtFp);
                        }
                        aggregationIndex.put(_srcElem, _newTgt);
                    }
                    _created.add(_newTgt);
                }
            }

            // Step 4: delete target elements whose group no longer exists in source
            for (bags2.Element _existingTgt : _existingInParent.values()) {
                if (!_processedTargets.contains(_existingTgt)) {
                    EcoreUtil.delete(_existingTgt, true);
                }
            }
        }

        // Step 5: clean up stale aggregation CEs (source element was deleted → null in corr)
        for (EObject _entry : new java.util.ArrayList<>(CorrespondenceModel.findDeletedAggregationSourceEntries(corrResource))) {
            CorrespondenceModel.removeCorrespondenceEntry(corrResource, _entry);
        }
    }

    /**
     * Phase 1d backward (incremental): syncs source element count to target multiplicity.
     * Creates new source elements when multiplicity increases; deletes when it decreases.
     */
    @SuppressWarnings("unchecked")
    private static void materializeAggregationBackElementIncremental(
            Resource targetModel, Resource sourceModel,
            Resource corrResource,
            com.google.common.collect.BiMap<EObject, EObject> corrIndex,
            java.util.Map<EObject, EObject> aggregationIndex,
            List<EObject> _created, List<EObject> _updated) {

        // Build reverse index: target element → list of existing source elements
        java.util.Map<EObject, java.util.List<EObject>> _reverseIdx =
            CorrespondenceModel.buildReverseAggregationIndex(corrResource);

        for (EObject _obj : allSourceObjects(targetModel)) {
            if (!(_obj instanceof bags2.Element _tgtElem)) continue;
            EObject _tgtBagObj = _tgtElem.eContainer();
            if (!(_tgtBagObj instanceof bags2.MyBag _tgtBag)) continue;
            EObject _srcBagObj = corrIndex.inverse().get(_tgtBag);
            if (!(_srcBagObj instanceof bags1.MyBag _srcBag)) continue;

            int _expectedCount = _tgtElem.getMultiplicity();
            String _value = _tgtElem.getValue();
            java.util.List<EObject> _existing = _reverseIdx.getOrDefault(_tgtElem, new java.util.ArrayList<>());
            int _currentCount = _existing.size();

            // Update groupBySourceAttr on existing source elements if value changed
            for (EObject _srcElemObj : _existing) {
                if (_srcElemObj instanceof bags1.Element _srcElem) {
                    if (!_value.equals(_srcElem.getValue())) {
                        _srcElem.setValue(_value);
                        Optional<EObject> _ceOpt = CorrespondenceModel.findBySource(corrResource, _srcElem);
                        _ceOpt.ifPresent(ce -> {
                            CorrespondenceModel.updateFingerprint(ce, computeFingerprint(_srcElem));
                            CorrespondenceModel.updateTargetFingerprint(ce, computeFingerprintBack(_tgtElem));
                        });
                        _updated.add(_srcElem);
                    }
                }
            }

            if (_currentCount < _expectedCount) {
                // Create additional source elements
                String _tgtFp = computeFingerprintBack(_tgtElem);
                for (int _i = _currentCount; _i < _expectedCount; _i++) {
                    bags1.Element _newSrc = Bags1Factory.eINSTANCE.createElement();
                    _newSrc.setValue(_value);
                    _srcBag.getElements().add(_newSrc);
                    String _srcFp = computeFingerprint(_newSrc);
                    CorrespondenceModel.addAggregationEntry(corrResource, _newSrc, "Element", _srcFp, _tgtElem, "Element", _tgtFp);
                    aggregationIndex.put(_newSrc, _tgtElem);
                    _created.add(_newSrc);
                }
            } else if (_currentCount > _expectedCount) {
                // Delete excess source elements (remove from the end)
                for (int _i = _expectedCount; _i < _currentCount; _i++) {
                    EObject _toRemove = _existing.get(_i);
                    EcoreUtil.delete(_toRemove, true);
                    CorrespondenceModel.removeEntry(corrResource, _toRemove);
                }
            }
        }

        // Clean up stale aggregation CEs (target element was deleted → null in corr)
        for (EObject _entry : new java.util.ArrayList<>(CorrespondenceModel.findDeletedAggregationTargetEntries(corrResource))) {
            // Cascade: delete the corresponding source element if still present
            EObject _srcObj = CorrespondenceModel.getSourceObject(_entry);
            if (_srcObj != null && _srcObj.eResource() != null) {
                EcoreUtil.delete(_srcObj, true);
            }
            CorrespondenceModel.removeCorrespondenceEntry(corrResource, _entry);
        }
    }

    /** Creates a new target object for the given source EObject, or null if no mapping exists. */
    private static EObject createNewTargetObject(EObject srcObj, Options options) {
        if (srcObj instanceof bags1.MyBag src) {
            return transformMyBag(src, options);
        }
        return null;
    }

    /**
     * Returns true if the given source object is covered by a TypeMapping.
     * Used to exclude role-based source types from Phase 1 of transformIncremental,
     * so their change signal is preserved for mapRoleBasedTypesIncremental (Phase 1b).
     */
    private static boolean isCoveredByTypeMappingSource(EObject srcObj) {
        if (srcObj instanceof bags1.MyBag) return true;
        return false;
    }

    /**
     * Returns true if the given target object is covered by a TypeMapping.
     * Used to exclude role-based target types from Phase 1 of transformIncrementalBack,
     * so their change signal is preserved for mapRoleBasedTypesIncrementalBack (Phase 1b).
     */
    private static boolean isCoveredByTypeMappingTarget(EObject tgtObj) {
        if (tgtObj instanceof bags2.MyBag) return true;
        return false;
    }

    /** Updates the target object's attributes to reflect changes in the source object. */
    private static void updateTargetAttributes(EObject srcObj, EObject tgtObj, Options options) {
        if (srcObj instanceof bags1.MyBag source
                && tgtObj instanceof bags2.MyBag target) {
        }
    }

    /**
     * Adds a newly created target object to its correct containment in the target model.
     * Uses the corrIndex to find the corresponding target parent.
     */
    private static void addToTargetContainment(
            EObject srcObj, EObject newTarget,
            Resource existingTarget,
            com.google.common.collect.BiMap<EObject, EObject> corrIndex) {
        EObject srcParent = srcObj.eContainer();
        if (srcParent == null) {
            existingTarget.getContents().add(newTarget);
            return;
        }
        EObject targetParent = corrIndex.get(srcParent);
        if (targetParent == null) return;

        // Reflective fallback: if no explicit mapping matched, use the source containment
        // feature name to locate the corresponding containment feature on the target parent.
        // Handles cases where the LLM omits the containment referenceMapping (e.g. same-named features).
        if (newTarget.eContainer() == null && srcObj.eContainmentFeature() != null) {
            org.eclipse.emf.ecore.EStructuralFeature _tgtFeat =
                    targetParent.eClass().getEStructuralFeature(srcObj.eContainmentFeature().getName());
            if (_tgtFeat instanceof org.eclipse.emf.ecore.EReference _tgtRef && _tgtRef.isContainment()) {
                if (_tgtRef.isMany()) {
                    @SuppressWarnings("unchecked")
                    EList<EObject> _tgtList = (EList<EObject>) targetParent.eGet(_tgtRef);
                    _tgtList.add(newTarget);
                } else {
                    targetParent.eSet(_tgtRef, newTarget);
                }
            }
        }
    }

    // ════════════════════════════════════════════════════════════════════════
    // Backward Incremental Helper Methods
    // ════════════════════════════════════════════════════════════════════════

    /**
     * Computes a fingerprint string for a target EObject (used for backward incremental detection).
     * Uses targetKeyAttributes from TypeMapping/RoleBasedTypeMapping; falls back to all attributes.
     */
    private static String computeFingerprintBack(EObject obj) {
        StringBuilder sb = new StringBuilder();
        sb.append(obj.eClass().getName()).append(":");
        if (obj instanceof bags2.MyBag typed) {
            for (EAttribute ea : obj.eClass().getEAllAttributes()) {
                if ("incrementalID".equals(ea.getName())) continue;
                sb.append(obj.eGet(ea)).append("|");
            }
            return sb.toString();
        }
        if (obj instanceof bags2.Element typed) {
            sb.append(typed.getValue()).append("|");
            // Non-key attributes for change detection
            for (EAttribute ea : obj.eClass().getEAllAttributes()) {
                if ("value".equals(ea.getName()) || "incrementalID".equals(ea.getName())) continue;
                sb.append(obj.eGet(ea)).append("|");
            }
            return sb.toString();
        }
        // Generic fallback: all attributes reflectively
        for (EAttribute ea : obj.eClass().getEAllAttributes()) {
            if ("incrementalID".equals(ea.getName())) continue;
            sb.append(obj.eGet(ea)).append("|");
        }
        return sb.toString();
    }

    /**
     * Computes the expected target fingerprint for a source object as if it were transformed forward.
     * Used in sync() for fuzzy matching: links existing unmatched objects instead of creating new ones.
     * Returns null if no mapping applies.
     */
    private static String computeExpectedTargetFingerprint(EObject srcObj) {
        // TypeMapping types: create a temporary target and compute its fingerprint.
        EObject _tmp = createNewTargetObject(srcObj, Options.defaults());
        if (_tmp != null) return computeFingerprintBack(_tmp);
        return null;
    }

    /**
     * Computes the expected source fingerprint for a target object as if it were transformed backward.
     * Used in sync() for fuzzy matching: links existing unmatched objects instead of creating new ones.
     * Returns null if no mapping applies.
     */
    private static String computeExpectedSourceFingerprint(EObject tgtObj) {
        // TypeMapping types: create a temporary source and compute its fingerprint.
        EObject _tmp = createNewSourceObject(tgtObj, Options.defaults());
        if (_tmp != null) return computeFingerprint(_tmp);
        return null;
    }

    /** Creates a new source object for the given target EObject, or null if no mapping exists. */
    private static EObject createNewSourceObject(EObject tgtObj, Options options) {
        if (tgtObj instanceof bags2.MyBag tgt) {
            return transformBackMyBagAsMyBag(tgt, options);
        }
        return null;
    }

    /**
     * Updates the source object's attributes to reflect changes in the target object (backward).
     * Handles both TypeMapping attribute expressions and role-based simple attribute updates.
     * Structural changes (e.g. moving a FamilyMember to a different Family) are handled
     * by mapRoleBasedTypesIncrementalBack after this method runs.
     */
    @SuppressWarnings("unchecked")
    private static void updateSourceAttributes(EObject tgtObj, EObject srcObj, Options options) {
        if (tgtObj instanceof bags2.MyBag target
                && srcObj instanceof bags1.MyBag source) {
        }
    }

    /**
     * Adds a newly created source object to its correct containment in the source model.
     * Uses corrIndex.inverse() to find the corresponding source parent from the target parent.
     */
    private static void addToSourceContainment(
            EObject tgtObj, EObject newSource,
            Resource existingSource,
            com.google.common.collect.BiMap<EObject, EObject> corrIndex) {
        EObject tgtParent = tgtObj.eContainer();
        if (tgtParent == null) {
            existingSource.getContents().add(newSource);
            return;
        }
        EObject srcParent = corrIndex.inverse().get(tgtParent);
        if (srcParent == null) return;

        // Reflective fallback: if no explicit mapping matched, use the target containment
        // feature name to locate the corresponding containment feature on the source parent.
        if (newSource.eContainer() == null && tgtObj.eContainmentFeature() != null) {
            org.eclipse.emf.ecore.EStructuralFeature _srcFeat =
                    srcParent.eClass().getEStructuralFeature(tgtObj.eContainmentFeature().getName());
            if (_srcFeat instanceof org.eclipse.emf.ecore.EReference _srcRef && _srcRef.isContainment()) {
                if (_srcRef.isMany()) {
                    @SuppressWarnings("unchecked")
                    EList<EObject> _srcList = (EList<EObject>) srcParent.eGet(_srcRef);
                    _srcList.add(newSource);
                } else {
                    srcParent.eSet(_srcRef, newSource);
                }
            }
        }
    }

    // ════════════════════════════════════════════════════════════════════════
    // Single-Object Transformation Methods (kept for backwards compatibility)
    // ════════════════════════════════════════════════════════════════════════

    /**
     * Transforms a single MyBag object.
     * @deprecated Use transform(Resource, Resource) for full model transformation.
     */
    @Deprecated
    public static bags2.MyBag transform(bags1.MyBag source) {
        return transformMyBag(source, Options.defaults());
    }

    /**
     * Transforms a single MyBag object back.
     * @deprecated Use transformBack(Resource, Resource) for full model transformation.
     */
    @Deprecated
    public static bags1.MyBag transformBack(bags2.MyBag target) {
        return transformBackMyBagAsMyBag(target, Options.defaults());
    }

    // ════════════════════════════════════════════════════════════════════════
    // Synchronisation: sync() — both models changed independently
    // ════════════════════════════════════════════════════════════════════════

    /**
     * BEKANNTER RANDFALL – Delete-Recreate mit gleichem Fingerprint:
     *
     * Wenn ein Objekt gelöscht und ein neues Objekt mit identischem
     * Fingerprint (gleiche Schlüsselattribute) angelegt wird, hat das
     * neue Objekt keinen Korrespondenzeintrag. Es wird daher in
     * Schritt 5 als "neu" behandelt und erneut transformiert, obwohl
     * es konzeptuell ein Update des gelöschten Objekts sein könnte.
     *
     * Konsequenz: Im Zielmodell entsteht ein neues Objekt, während
     * das alte Zielobjekt über den verwaisten corrEntry (Partition 4)
     * gelöscht wird. Das Ergebnis ist funktional korrekt, aber
     * Querverweise anderer Objekte auf das alte Zielobjekt gehen
     * verloren (sie zeigen nach dem Sync ins Leere, bis Phase 6
     * Cross-References neu auflöst).
     *
     * Lösungsansatz für spätere Ausbaustufen: Persistente Objekt-IDs
     * (XMI-IDs) statt Fingerprinting als primäre Identifikation.
     * Dann ist Delete-Recreate eindeutig vom echten Neuanlegen
     * unterscheidbar.
     *
     * Siehe auch: PROJECT_OVERVIEW.md, Bekannte Einschränkungen Nr. 2
     */
    public static SyncResult sync(Resource source, Resource target, Resource corrModel) {
        return sync(source, target, corrModel,
                SyncConflictPolicy.SOURCE_WINS,
                TransformationContext.DeletionPolicy.TOMBSTONE,
                Options.defaults(),
                PostProcessor.NOOP, PostProcessor.NOOP);
    }

    public static SyncResult sync(
            Resource source,
            Resource target,
            Resource corrModel,
            SyncConflictPolicy conflictPolicy,
            TransformationContext.DeletionPolicy deletionPolicy,
            Options options) {
        return sync(source, target, corrModel, conflictPolicy, deletionPolicy, options,
                PostProcessor.NOOP, PostProcessor.NOOP);
    }

    /**
     * Synchronises source and target using separate post-processors per direction.
     * forwardPostProcessor.afterTransform is called with newly created/updated target objects.
     * backwardPostProcessor.afterTransform is called with newly created/updated source objects.
     * Note: beforeDeletions is not invoked by sync() — objects are deleted externally
     * before sync() is called; their absence is detected via null corrEntry references.
     */
    @SuppressWarnings("unchecked")
    public static SyncResult sync(
            Resource source,
            Resource target,
            Resource corrModel,
            SyncConflictPolicy conflictPolicy,
            TransformationContext.DeletionPolicy deletionPolicy,
            Options options,
            PostProcessor forwardPostProcessor,
            PostProcessor backwardPostProcessor) {

        com.google.common.collect.BiMap<EObject, EObject> corrIndex = CorrespondenceModel.buildIndex(corrModel);
        int _updFwd = 0, _updBwd = 0, _crFwd = 0, _crBwd = 0, _del = 0, _linked = 0;
        java.util.List<SyncConflict> _conflicts = new java.util.ArrayList<>();
        java.util.List<EObject> _fwdCreated = new java.util.ArrayList<>();
        java.util.List<EObject> _fwdUpdated = new java.util.ArrayList<>();
        java.util.List<EObject> _bwdCreated = new java.util.ArrayList<>();
        java.util.List<EObject> _bwdUpdated = new java.util.ArrayList<>();

        // Snapshot to avoid ConcurrentModificationException while removing Partition 4 entries.
        java.util.List<EObject> _allEntries = CorrespondenceModel.getAllEntries(corrModel);

        // ── Schritt 1: Partition 1 (src ≠ null, tgt ≠ null) ─────────────────
        for (EObject _ce : _allEntries) {
            EObject _srcObj = CorrespondenceModel.getSourceObject(_ce);
            EObject _tgtObj = CorrespondenceModel.getTargetObject(_ce);
            if (_srcObj == null || _tgtObj == null) continue;

            String _storedSrcFp = CorrespondenceModel.getFingerprint(_ce);
            String _storedTgtFp = CorrespondenceModel.getTargetFingerprint(_ce);
            if (_storedSrcFp == null) _storedSrcFp = "";
            if (_storedTgtFp == null) _storedTgtFp = "";

            String _curSrcFp = computeFingerprint(_srcObj);
            String _curTgtFp = computeFingerprintBack(_tgtObj);
            boolean _srcChg = !_curSrcFp.equals(_storedSrcFp);
            boolean _tgtChg = !_curTgtFp.equals(_storedTgtFp);

            if (!_srcChg && !_tgtChg) continue; // Fall D: nothing to do

            if (!isCoveredByTypeMappingSource(_srcObj)) {
                // Role-based type: steer mapRoleBasedTypesIncremental/Back via fingerprint neutralisation.
                if (_srcChg && _tgtChg) {
                    switch (conflictPolicy) {
                        case SOURCE_WINS ->
                            // Neutralise backward: stored tgtFp ← current tgtFp
                            CorrespondenceModel.updateTargetFingerprint(_ce, _curTgtFp);
                        case TARGET_WINS ->
                            // Neutralise forward: stored srcFp ← current srcFp
                            CorrespondenceModel.updateFingerprint(_ce, _curSrcFp);
                        case LOG_AND_SKIP -> {
                            CorrespondenceModel.updateFingerprint(_ce, _curSrcFp);
                            CorrespondenceModel.updateTargetFingerprint(_ce, _curTgtFp);
                            _conflicts.add(new SyncConflict(_srcObj, _tgtObj,
                                    _srcObj.eClass().getName(), _tgtObj.eClass().getName(),
                                    _storedSrcFp, _curSrcFp, _storedTgtFp, _curTgtFp));
                        }
                    }
                }
                // Falls A and B are handled naturally by mapRoleBasedTypesIncremental/Back.
                continue;
            }

            // TypeMapping type: handle inline.
            if (_srcChg && !_tgtChg) {
                // Fall A: source changed → forward propagate
                updateTargetAttributes(_srcObj, _tgtObj, options);
                CorrespondenceModel.updateFingerprint(_ce, _curSrcFp);
                CorrespondenceModel.updateTargetFingerprint(_ce, computeFingerprintBack(_tgtObj));
                _updFwd++; _fwdUpdated.add(_tgtObj);
            } else if (!_srcChg && _tgtChg) {
                // Fall B: target changed → backward propagate
                updateSourceAttributes(_tgtObj, _srcObj, options);
                CorrespondenceModel.updateTargetFingerprint(_ce, _curTgtFp);
                CorrespondenceModel.updateFingerprint(_ce, computeFingerprint(_srcObj));
                _updBwd++; _bwdUpdated.add(_srcObj);
            } else {
                // Fall C: conflict
                switch (conflictPolicy) {
                    case SOURCE_WINS -> {
                        updateTargetAttributes(_srcObj, _tgtObj, options);
                        CorrespondenceModel.updateFingerprint(_ce, _curSrcFp);
                        CorrespondenceModel.updateTargetFingerprint(_ce, computeFingerprintBack(_tgtObj));
                        _updFwd++; _fwdUpdated.add(_tgtObj);
                    }
                    case TARGET_WINS -> {
                        updateSourceAttributes(_tgtObj, _srcObj, options);
                        CorrespondenceModel.updateTargetFingerprint(_ce, _curTgtFp);
                        CorrespondenceModel.updateFingerprint(_ce, computeFingerprint(_srcObj));
                        _updBwd++; _bwdUpdated.add(_srcObj);
                    }
                    case LOG_AND_SKIP -> _conflicts.add(new SyncConflict(_srcObj, _tgtObj,
                            _srcObj.eClass().getName(), _tgtObj.eClass().getName(),
                            _storedSrcFp, _curSrcFp, _storedTgtFp, _curTgtFp));
                }
            }
        }

        // ── Schritt 2: Partition 2 (src ≠ null, tgt = null) — TypeMapping ──
        for (EObject _ce : _allEntries) {
            EObject _srcObj = CorrespondenceModel.getSourceObject(_ce);
            if (_srcObj == null || CorrespondenceModel.getTargetObject(_ce) != null) continue;
            if (!isCoveredByTypeMappingSource(_srcObj)) continue;
            EObject _newTgt = createNewTargetObject(_srcObj, options);
            if (_newTgt != null) {
                addToTargetContainment(_srcObj, _newTgt, target, corrIndex);
                String _tgtCR = _newTgt.eContainmentFeature() != null ? _newTgt.eContainmentFeature().getName() : "";
                CorrespondenceModel.updateTargetObject(_ce, _newTgt, _newTgt.eClass().getName());
                CorrespondenceModel.updateTargetFingerprint(_ce, computeFingerprintBack(_newTgt));
                CorrespondenceModel.updateTargetContainmentRole(_ce, _tgtCR);
                corrIndex.put(_srcObj, _newTgt);
                _crFwd++; _fwdCreated.add(_newTgt);
            }
        }

        // ── Schritt 3: Partition 3 (src = null, tgt ≠ null) — TypeMapping ──
        for (EObject _ce : _allEntries) {
            EObject _tgtObj = CorrespondenceModel.getTargetObject(_ce);
            if (_tgtObj == null || CorrespondenceModel.getSourceObject(_ce) != null) continue;
            if (!isCoveredByTypeMappingTarget(_tgtObj)) continue;
            EObject _newSrc = createNewSourceObject(_tgtObj, options);
            if (_newSrc != null) {
                addToSourceContainment(_tgtObj, _newSrc, source, corrIndex);
                String _srcCR = _newSrc.eContainmentFeature() != null ? _newSrc.eContainmentFeature().getName() : "";
                CorrespondenceModel.updateSourceObject(_ce, _newSrc, _newSrc.eClass().getName());
                CorrespondenceModel.updateFingerprint(_ce, computeFingerprint(_newSrc));
                CorrespondenceModel.updateSourceContainmentRole(_ce, _srcCR);
                corrIndex.put(_newSrc, _tgtObj);
                _crBwd++; _bwdCreated.add(_newSrc);
            }
        }

        // ── Schritt 4: Partition 4 (both null) ───────────────────────────────
        for (EObject _ce : _allEntries) {
            if (CorrespondenceModel.getSourceObject(_ce) == null
                    && CorrespondenceModel.getTargetObject(_ce) == null) {
                CorrespondenceModel.removeCorrespondenceEntry(corrModel, _ce);
                _del++;
            }
        }

        // ── Schritt 5a: Fuzzy-Match ──────────────────────────────────────────
        // Versuche, ungematchte Objekte beider Seiten durch Fingerprint-Vergleich
        // zu verbinden, bevor neue Objekte erstellt werden.
        // Vorwärts: Index ungematchter Zielobjekte nach Backward-Fingerprint.
        {
            java.util.Map<String, EObject> _unmatchedTgtByFP = new java.util.HashMap<>();
            for (EObject _obj : allSourceObjects(target)) {
                if (!corrIndex.containsValue(_obj)) {
                    String _fp = computeFingerprintBack(_obj);
                    if (_fp != null) _unmatchedTgtByFP.putIfAbsent(_fp, _obj);
                }
            }
            for (EObject _srcObj : allSourceObjects(source)) {
                if (corrIndex.containsKey(_srcObj)) continue;
                String _eFP = computeExpectedTargetFingerprint(_srcObj);
                if (_eFP != null && _unmatchedTgtByFP.containsKey(_eFP)) {
                    EObject _tgtObj = _unmatchedTgtByFP.remove(_eFP);
                    String _srcCR = _srcObj.eContainmentFeature() != null ? _srcObj.eContainmentFeature().getName() : "";
                    String _tgtCR = _tgtObj.eContainmentFeature() != null ? _tgtObj.eContainmentFeature().getName() : "";
                    CorrespondenceModel.addEntry(corrModel,
                            _srcObj, _srcObj.eClass().getName(), computeFingerprint(_srcObj),
                            _tgtObj, _tgtObj.eClass().getName(), computeFingerprintBack(_tgtObj), _srcCR, _tgtCR);
                    corrIndex.put(_srcObj, _tgtObj);
                    _linked++;
                }
            }
            // Rückwärts: Index ungematchter Quellobjekte nach Forward-Fingerprint.
            java.util.Map<String, EObject> _unmatchedSrcByFP = new java.util.HashMap<>();
            for (EObject _obj : allSourceObjects(source)) {
                if (!corrIndex.containsKey(_obj)) {
                    String _fp = computeFingerprint(_obj);
                    if (_fp != null) _unmatchedSrcByFP.putIfAbsent(_fp, _obj);
                }
            }
            for (EObject _tgtObj : allSourceObjects(target)) {
                if (corrIndex.containsValue(_tgtObj)) continue;
                String _eFP = computeExpectedSourceFingerprint(_tgtObj);
                if (_eFP != null && _unmatchedSrcByFP.containsKey(_eFP)) {
                    EObject _srcObj = _unmatchedSrcByFP.remove(_eFP);
                    String _srcCR = _srcObj.eContainmentFeature() != null ? _srcObj.eContainmentFeature().getName() : "";
                    String _tgtCR = _tgtObj.eContainmentFeature() != null ? _tgtObj.eContainmentFeature().getName() : "";
                    CorrespondenceModel.addEntry(corrModel,
                            _srcObj, _srcObj.eClass().getName(), computeFingerprint(_srcObj),
                            _tgtObj, _tgtObj.eClass().getName(), computeFingerprintBack(_tgtObj), _srcCR, _tgtCR);
                    corrIndex.put(_srcObj, _tgtObj);
                    _linked++;
                }
            }
        }

        // ── Schritt 5: New objects without corrEntry — TypeMapping ───────────
        for (EObject _srcObj : allSourceObjects(source)) {
            if (!isCoveredByTypeMappingSource(_srcObj)) continue;
            if (corrIndex.containsKey(_srcObj)) continue;
            EObject _newTgt = createNewTargetObject(_srcObj, options);
            if (_newTgt != null) {
                addToTargetContainment(_srcObj, _newTgt, target, corrIndex);
                String _srcCR = _srcObj.eContainmentFeature() != null ? _srcObj.eContainmentFeature().getName() : "";
                String _tgtCR = _newTgt.eContainmentFeature() != null ? _newTgt.eContainmentFeature().getName() : "";
                CorrespondenceModel.addEntry(corrModel,
                        _srcObj, _srcObj.eClass().getName(), computeFingerprint(_srcObj),
                        _newTgt, _newTgt.eClass().getName(), computeFingerprintBack(_newTgt), _srcCR, _tgtCR);
                corrIndex.put(_srcObj, _newTgt);
                _crFwd++; _fwdCreated.add(_newTgt);
            }
        }
        for (EObject _tgtObj : allSourceObjects(target)) {
            if (!isCoveredByTypeMappingTarget(_tgtObj)) continue;
            if (corrIndex.inverse().containsKey(_tgtObj)) continue;
            EObject _newSrc = createNewSourceObject(_tgtObj, options);
            if (_newSrc != null) {
                addToSourceContainment(_tgtObj, _newSrc, source, corrIndex);
                String _srcCR = _newSrc.eContainmentFeature() != null ? _newSrc.eContainmentFeature().getName() : "";
                String _tgtCR = _tgtObj.eContainmentFeature() != null ? _tgtObj.eContainmentFeature().getName() : "";
                CorrespondenceModel.addEntry(corrModel,
                        _newSrc, _newSrc.eClass().getName(), computeFingerprint(_newSrc),
                        _tgtObj, _tgtObj.eClass().getName(), computeFingerprintBack(_tgtObj), _srcCR, _tgtCR);
                corrIndex.put(_newSrc, _tgtObj);
                _crBwd++; _bwdCreated.add(_newSrc);
            }
        }


        // ── Phase 1c: Edge materialization ──────────────────────────────────

        // ── Schritt 6: Cross-references ──────────────────────────────────────
        // Rebuild corrIndex after all structural changes.
        corrIndex = CorrespondenceModel.buildIndex(corrModel);

        CorrespondenceModel.saveAndUpdateTimestamp(corrModel);

        // Post-processing: rebuild corrIndex so hooks see final cross-reference state.
        com.google.common.collect.BiMap<EObject, EObject> _finalIndex = CorrespondenceModel.buildIndex(corrModel);
        forwardPostProcessor.afterTransform(source, target, _finalIndex, _fwdCreated, _fwdUpdated);
        backwardPostProcessor.afterTransform(target, source, _finalIndex.inverse(), _bwdCreated, _bwdUpdated);

        return new SyncResult(_updFwd, _updBwd, _crFwd, _crBwd, _del, _linked, _conflicts);
    }
}
