package de.tbuchmann.bxagent.pdb12pdb2;

// EMF imports for source and target packages
import pdb1.*;
import pdb2.*;
import org.eclipse.emf.ecore.*;
import org.eclipse.emf.ecore.resource.*;
import org.eclipse.emf.ecore.util.EcoreUtil;
import java.util.*;

/**
 * Bidirectional EMF transformation: pdb1 ↔ pdb2
 * Generated by emt-agent.
 *
 * WARNING: Do not edit manually - will be overwritten on regeneration.
 */
public class Pdb12Pdb2GenTransformation {

    // ════════════════════════════════════════════════════════════════════════
    // Transformation Options
    // ════════════════════════════════════════════════════════════════════════

    /**
     * Configuration options for non-deterministic transformation steps.
     * Pass to transform() or transformBack() to control ambiguous mappings.
     */
    public record Options(
        String nameBackwardSplitStrategy  // Controls how to split the concatenated name field during backward transformation: 'first' splits at the first blank, 'last' splits at the last blank.
    ) {
        /** Default options. */
        public static Options defaults() {
            return new Options(
                "first"
            );
        }
    }

    // ════════════════════════════════════════════════════════════════════════
    // Public Entry Points - Resource-level Transformation
    // ════════════════════════════════════════════════════════════════════════

    /**
     * Transforms the contents of sourceResource into targetResource using default options.
     * Both resources must already exist and the root elements must be pre-created.
     *
     * @param sourceResource Source EMF resource (read)
     * @param targetResource Target EMF resource (written into, root elements must exist)
     */
    public static void transform(Resource sourceResource, Resource targetResource) {
        transform(sourceResource, targetResource, Options.defaults());
    }

    /**
     * Transforms the contents of sourceResource into targetResource.
     * Both resources must already exist and the root elements must be pre-created.
     * Uses two-phase transformation: (1) create contained objects, (2) resolve cross-references.
     *
     * @param sourceResource Source EMF resource (read)
     * @param targetResource Target EMF resource (written into, root elements must exist)
     * @param options Configuration options for non-deterministic mappings
     */
    public static void transform(Resource sourceResource, Resource targetResource, Options options) {
        if (sourceResource == null || targetResource == null) {
            return;
        }

        // Object mapping for cross-reference resolution
        Map<EObject, EObject> objectMap = new HashMap<>();
        Set<EObject> visited = new HashSet<>();

        // Pre-populate objectMap with existing root element pairs (by index)
        // and apply root-type attribute mappings
        List<EObject> sourceRoots = sourceResource.getContents();
        List<EObject> targetRoots = targetResource.getContents();
        for (int i = 0; i < Math.min(sourceRoots.size(), targetRoots.size()); i++) {
            pdb1.Database source = (pdb1.Database) sourceRoots.get(i);
            pdb2.Database target = (pdb2.Database) targetRoots.get(i);
            target.setName(source.getName());
            objectMap.put(source, target);
        }

        // Phase 1: Traverse containment hierarchy and create contained objects
        for (EObject sourceRoot : sourceRoots) {
            createAndMapObjects(sourceRoot, objectMap, visited, options);
        }

        // Phase 2: Resolve all cross-references
        resolveReferences(objectMap);
    }

    /**
     * Transforms the contents of targetResource back into sourceResource using default options.
     * Both resources must already exist and the root elements must be pre-created.
     *
     * @param targetResource Target EMF resource (read)
     * @param sourceResource Source EMF resource (written into, root elements must exist)
     */
    public static void transformBack(Resource targetResource, Resource sourceResource) {
        transformBack(targetResource, sourceResource, Options.defaults());
    }

    /**
     * Transforms the contents of targetResource back into sourceResource.
     * Both resources must already exist and the root elements must be pre-created.
     * Uses two-phase transformation: (1) create contained objects, (2) resolve cross-references.
     *
     * @param targetResource Target EMF resource (read)
     * @param sourceResource Source EMF resource (written into, root elements must exist)
     * @param options Configuration options for non-deterministic mappings
     */
    public static void transformBack(Resource targetResource, Resource sourceResource, Options options) {
        if (targetResource == null || sourceResource == null) {
            return;
        }

        // Object mapping for cross-reference resolution
        Map<EObject, EObject> objectMap = new HashMap<>();
        Set<EObject> visited = new HashSet<>();

        // Pre-populate objectMap with existing root element pairs (by index)
        // and apply root-type backward attribute mappings
        List<EObject> targetRoots = targetResource.getContents();
        List<EObject> sourceRoots = sourceResource.getContents();
        for (int i = 0; i < Math.min(targetRoots.size(), sourceRoots.size()); i++) {
            pdb2.Database target = (pdb2.Database) targetRoots.get(i);
            pdb1.Database source = (pdb1.Database) sourceRoots.get(i);
            source.setName(target.getName());
            objectMap.put(target, source);
        }

        // Phase 1: Traverse containment hierarchy and create contained objects
        for (EObject targetRoot : targetRoots) {
            createAndMapObjectsBack(targetRoot, objectMap, visited, options);
        }

        // Phase 2: Resolve all cross-references
        resolveReferencesBack(objectMap);
    }

    // ════════════════════════════════════════════════════════════════════════
    // Phase 1: Object Creation and Attribute Mapping (Forward)
    // ════════════════════════════════════════════════════════════════════════

    /**
     * Recursively creates target objects for source object tree (containments only).
     * Maps attributes and stores source→target mapping.
     * Pre-existing entries in objectMap (e.g. root elements) are traversed but not recreated.
     */
    private static EObject createAndMapObjects(EObject source, Map<EObject, EObject> objectMap, Set<EObject> visited, Options options) {
        if (source == null) {
            return null;
        }

        // Use visited set to prevent infinite loops (objectMap alone is not enough
        // since root elements are pre-seeded and must still be traversed)
        if (visited.contains(source)) {
            return objectMap.get(source);
        }
        visited.add(source);

        EObject target;
        if (objectMap.containsKey(source)) {
            // Pre-existing entry (e.g. root element) — use it, still traverse children
            target = objectMap.get(source);
        } else {
            target = null;

            // Handle Database → Database
            if (source instanceof pdb1.Database) {
                target = transformDatabase((pdb1.Database) source, options);
            } else
            // Handle Person → Person
            if (source instanceof pdb1.Person) {
                target = transformPerson((pdb1.Person) source, options);
            }

            if (target != null) {
                objectMap.put(source, target);
            }
        }

        if (target != null) {

            // Recursively transform containment references
            // Containment: Database.persons → Database.persons
            if (source instanceof pdb1.Database && target instanceof pdb2.Database) {
                for (pdb1.Person child : ((pdb1.Database) source).getPersons()) {
                    EObject transformedChild = createAndMapObjects(child, objectMap, visited, options);
                    if (transformedChild instanceof pdb2.Person) {
                        ((pdb2.Database) target).getPersons().add((pdb2.Person) transformedChild);
                    }
                }
            }
        }

        return target;
    }

    // ════════════════════════════════════════════════════════════════════════
    // Phase 2: Cross-Reference Resolution (Forward)
    // ════════════════════════════════════════════════════════════════════════

    /**
     * Resolves all cross-references (non-containment) using the object map.
     */
    private static void resolveReferences(Map<EObject, EObject> objectMap) {
        // No cross-references defined
    }

    // ════════════════════════════════════════════════════════════════════════
    // Phase 1: Object Creation and Attribute Mapping (Backward)
    // ════════════════════════════════════════════════════════════════════════

    /**
     * Recursively creates source objects for target object tree (containments only).
     * Maps attributes and stores target→source mapping.
     * Pre-existing entries in objectMap (e.g. root elements) are traversed but not recreated.
     */
    private static EObject createAndMapObjectsBack(EObject target, Map<EObject, EObject> objectMap, Set<EObject> visited, Options options) {
        if (target == null) {
            return null;
        }

        // Use visited set to prevent infinite loops (objectMap alone is not enough
        // since root elements are pre-seeded and must still be traversed)
        if (visited.contains(target)) {
            return objectMap.get(target);
        }
        visited.add(target);

        EObject source;
        if (objectMap.containsKey(target)) {
            // Pre-existing entry (e.g. root element) — use it, still traverse children
            source = objectMap.get(target);
        } else {
            source = null;

            // Handle Database → Database
            if (target instanceof pdb2.Database) {
                source = transformBackDatabase((pdb2.Database) target, options);
            } else
            // Handle Person → Person
            if (target instanceof pdb2.Person) {
                source = transformBackPerson((pdb2.Person) target, options);
            }

            if (source != null) {
                objectMap.put(target, source);
            }
        }

        if (source != null) {

            // Recursively transform containment references
            // Containment (backward): Database.persons → Database.persons
            if (target instanceof pdb2.Database && source instanceof pdb1.Database) {
                for (pdb2.Person child : ((pdb2.Database) target).getPersons()) {
                    EObject transformedChild = createAndMapObjectsBack(child, objectMap, visited, options);
                    if (transformedChild instanceof pdb1.Person) {
                        ((pdb1.Database) source).getPersons().add((pdb1.Person) transformedChild);
                    }
                }
            }
        }

        return source;
    }

    // ════════════════════════════════════════════════════════════════════════
    // Phase 2: Cross-Reference Resolution (Backward)
    // ════════════════════════════════════════════════════════════════════════

    /**
     * Resolves all cross-references (non-containment) using the object map.
     */
    private static void resolveReferencesBack(Map<EObject, EObject> objectMap) {
        // No cross-references defined
    }

    // ════════════════════════════════════════════════════════════════════════
    // Single-Object Transformation Methods (kept for backwards compatibility)
    // ════════════════════════════════════════════════════════════════════════

    /**
     * Transforms a single Database object.
     * @deprecated Use transform(Resource, Resource) for full model transformation.
     */
    @Deprecated
    public static pdb2.Database transform(pdb1.Database source) {
        return transformDatabase(source, Options.defaults());
    }

    /**
     * Transforms a single Database object back.
     * @deprecated Use transformBack(Resource, Resource) for full model transformation.
     */
    @Deprecated
    public static pdb1.Database transformBack(pdb2.Database target) {
        return transformBackDatabase(target, Options.defaults());
    }

    // ════════════════════════════════════════════════════════════════════════
    // Helper Methods for Type-Specific Transformations
    // ════════════════════════════════════════════════════════════════════════

    /**
     * Transforms Database → Database
     */
    private static pdb2.Database transformDatabase(pdb1.Database source, Options options) {
        if (source == null) {
            return null;
        }

        pdb2.Database target = Pdb2Factory.eINSTANCE.createDatabase();

        target.setName(source.getName());
        return target;
    }

    /**
     * Transforms Database → Database (backward)
     */
    private static pdb1.Database transformBackDatabase(pdb2.Database target, Options options) {
        if (target == null) {
            return null;
        }

        pdb1.Database source = Pdb1Factory.eINSTANCE.createDatabase();

        source.setName(target.getName());
        return source;
    }

    /**
     * Transforms Person → Person
     */
    private static pdb2.Person transformPerson(pdb1.Person source, Options options) {
        if (source == null) {
            return null;
        }

        pdb2.Person target = Pdb2Factory.eINSTANCE.createPerson();

        target.setName(source.getFirstName() + ' ' + source.getLastName());
        target.setName(source.getFirstName() + ' ' + source.getLastName());
        target.setBirthday(source.getBirthday());
        target.setPlaceOfBirth(source.getPlaceOfBirth());
        target.setId(source.getId());
        target.setIncrementalID(source.getIncrementalID());
        return target;
    }

    /**
     * Transforms Person → Person (backward)
     */
    private static pdb1.Person transformBackPerson(pdb2.Person target, Options options) {
        if (target == null) {
            return null;
        }

        pdb1.Person source = Pdb1Factory.eINSTANCE.createPerson();

        source.setFirstName(options.nameBackwardSplitStrategy().equals("first") ? (target.getName().contains(" ") ? target.getName().substring(0, target.getName().indexOf(' ')) : target.getName()) : (target.getName().contains(" ") ? target.getName().substring(0, target.getName().lastIndexOf(' ')) : target.getName()));
        source.setLastName(options.nameBackwardSplitStrategy().equals("first") ? (target.getName().contains(" ") ? target.getName().substring(target.getName().indexOf(' ') + 1) : "") : (target.getName().contains(" ") ? target.getName().substring(target.getName().lastIndexOf(' ') + 1) : target.getName()));
        source.setBirthday(target.getBirthday());
        source.setPlaceOfBirth(target.getPlaceOfBirth());
        source.setId(target.getId());
        source.setIncrementalID(target.getIncrementalID());
        return source;
    }

}
