package de.tbuchmann.bxagent.pdb12pdb2;

// EMF imports for source and target packages
import pdb1.*;
import pdb2.*;
import org.eclipse.emf.ecore.*;
import org.eclipse.emf.ecore.resource.*;
import org.eclipse.emf.ecore.resource.impl.ResourceSetImpl;
import org.eclipse.emf.ecore.xmi.impl.XMIResourceFactoryImpl;
import org.eclipse.emf.ecore.util.EcoreUtil;
import java.util.*;

/**
 * Bidirectional EMF transformation: pdb1 ↔ pdb2
 * Generated by emt-agent.
 *
 * WARNING: Do not edit manually - will be overwritten on regeneration.
 */
public class PersonToPersonTransformation {

    // ════════════════════════════════════════════════════════════════════════
    // Public Entry Points - Resource-level Transformation
    // ════════════════════════════════════════════════════════════════════════

    /**
     * Transforms the contents of sourceResource into targetResource.
     * Both resources must already exist and the root elements must be pre-created.
     * Uses two-phase transformation: (1) create contained objects, (2) resolve cross-references.
     *
     * @param sourceResource Source EMF resource (read)
     * @param targetResource Target EMF resource (written into, root elements must exist)
     */
    public static void transform(Resource sourceResource, Resource targetResource) {
        if (sourceResource == null || targetResource == null) {
            return;
        }

        // Object mapping for cross-reference resolution
        Map<EObject, EObject> objectMap = new HashMap<>();
        Set<EObject> visited = new HashSet<>();

        // Pre-populate objectMap with existing root element pairs (by index)
        List<EObject> sourceRoots = sourceResource.getContents();
        List<EObject> targetRoots = targetResource.getContents();
        for (int i = 0; i < Math.min(sourceRoots.size(), targetRoots.size()); i++) {
        	((pdb2.Database)targetRoots.get(i)).setName(((pdb1.Database)sourceRoots.get(i)).getName()); // Optional: set target root name to source root class name for clarity
            objectMap.put(sourceRoots.get(i), targetRoots.get(i));
        }

        // Phase 1: Traverse containment hierarchy and create contained objects
        for (EObject sourceRoot : sourceRoots) {
            createAndMapObjects(sourceRoot, objectMap, visited);
        }

        // Phase 2: Resolve all cross-references
        resolveReferences(objectMap);
    }

    /**
     * Transforms the contents of targetResource back into sourceResource.
     * Both resources must already exist and the root elements must be pre-created.
     * Uses two-phase transformation: (1) create contained objects, (2) resolve cross-references.
     *
     * @param targetResource Target EMF resource (read)
     * @param sourceResource Source EMF resource (written into, root elements must exist)
     */
    public static void transformBack(Resource targetResource, Resource sourceResource) {
        if (targetResource == null || sourceResource == null) {
            return;
        }

        // Object mapping for cross-reference resolution
        Map<EObject, EObject> objectMap = new HashMap<>();
        Set<EObject> visited = new HashSet<>();

        // Pre-populate objectMap with existing root element pairs (by index)
        List<EObject> targetRoots = targetResource.getContents();
        List<EObject> sourceRoots = sourceResource.getContents();
        for (int i = 0; i < Math.min(targetRoots.size(), sourceRoots.size()); i++) {
            objectMap.put(targetRoots.get(i), sourceRoots.get(i));
        }

        // Phase 1: Traverse containment hierarchy and create contained objects
        for (EObject targetRoot : targetRoots) {
            createAndMapObjectsBack(targetRoot, objectMap, visited);
        }

        // Phase 2: Resolve all cross-references
        resolveReferencesBack(objectMap);
    }

    // ════════════════════════════════════════════════════════════════════════
    // Phase 1: Object Creation and Attribute Mapping (Forward)
    // ════════════════════════════════════════════════════════════════════════

    /**
     * Recursively creates target objects for source object tree (containments only).
     * Maps attributes and stores source→target mapping.
     * Pre-existing entries in objectMap (e.g. root elements) are traversed but not recreated.
     */
    private static EObject createAndMapObjects(EObject source, Map<EObject, EObject> objectMap, Set<EObject> visited) {
        if (source == null) {
            return null;
        }

        // Use visited set to prevent infinite loops (objectMap alone is not enough
        // since root elements are pre-seeded and must still be traversed)
        if (visited.contains(source)) {
            return objectMap.get(source);
        }
        visited.add(source);

        EObject target;
        if (objectMap.containsKey(source)) {
            // Pre-existing entry (e.g. root element) — use it, still traverse children
            target = objectMap.get(source);
        } else {
            target = null;

            // Handle Person → Person
            if (source instanceof pdb1.Person) {
                target = transformPerson((pdb1.Person) source);
            } else
            // Handle Database → Database
            if (source instanceof pdb1.Database) {
                target = transformDatabase((pdb1.Database) source);
            }

            if (target != null) {
                objectMap.put(source, target);
            }
        }

        if (target != null) {

            // Recursively transform containment references
            // Containment: Database.persons → Database.persons
            if (source instanceof pdb1.Database && target instanceof pdb2.Database) {
                for (pdb1.Person child : ((pdb1.Database) source).getPersons()) {
                    EObject transformedChild = createAndMapObjects(child, objectMap, visited);
                    if (transformedChild instanceof pdb2.Person) {
                        ((pdb2.Database) target).getPersons().add((pdb2.Person) transformedChild);
                    }
                }
            }
        }

        return target;
    }

    // ════════════════════════════════════════════════════════════════════════
    // Phase 2: Cross-Reference Resolution (Forward)
    // ════════════════════════════════════════════════════════════════════════

    /**
     * Resolves all cross-references (non-containment) using the object map.
     */
    private static void resolveReferences(Map<EObject, EObject> objectMap) {
        // No cross-references defined
    }

    // ════════════════════════════════════════════════════════════════════════
    // Phase 1: Object Creation and Attribute Mapping (Backward)
    // ════════════════════════════════════════════════════════════════════════

    /**
     * Recursively creates source objects for target object tree (containments only).
     * Maps attributes and stores target→source mapping.
     * Pre-existing entries in objectMap (e.g. root elements) are traversed but not recreated.
     */
    private static EObject createAndMapObjectsBack(EObject target, Map<EObject, EObject> objectMap, Set<EObject> visited) {
        if (target == null) {
            return null;
        }

        // Use visited set to prevent infinite loops (objectMap alone is not enough
        // since root elements are pre-seeded and must still be traversed)
        if (visited.contains(target)) {
            return objectMap.get(target);
        }
        visited.add(target);

        EObject source;
        if (objectMap.containsKey(target)) {
            // Pre-existing entry (e.g. root element) — use it, still traverse children
            source = objectMap.get(target);
        } else {
            source = null;

            // Handle Person → Person
            if (target instanceof pdb2.Person) {
                source = transformBackPerson((pdb2.Person) target);
            } else
            // Handle Database → Database
            if (target instanceof pdb2.Database) {
                source = transformBackDatabase((pdb2.Database) target);
            }

            if (source != null) {
                objectMap.put(target, source);
            }
        }

        if (source != null) {

            // Recursively transform containment references
            // Containment (backward): Database.persons → Database.persons
            if (target instanceof pdb2.Database && source instanceof pdb1.Database) {
                for (pdb2.Person child : ((pdb2.Database) target).getPersons()) {
                    EObject transformedChild = createAndMapObjectsBack(child, objectMap, visited);
                    if (transformedChild instanceof pdb1.Person) {
                        ((pdb1.Database) source).getPersons().add((pdb1.Person) transformedChild);
                    }
                }
            }
        }

        return source;
    }

    // ════════════════════════════════════════════════════════════════════════
    // Phase 2: Cross-Reference Resolution (Backward)
    // ════════════════════════════════════════════════════════════════════════

    /**
     * Resolves all cross-references (non-containment) using the object map.
     */
    private static void resolveReferencesBack(Map<EObject, EObject> objectMap) {
        // No cross-references defined
    }

    // ════════════════════════════════════════════════════════════════════════
    // Single-Object Transformation Methods (kept for backwards compatibility)
    // ════════════════════════════════════════════════════════════════════════

    /**
     * Transforms a single Person object.
     * @deprecated Use transform(Resource, ResourceSet) for full model transformation.
     */
    @Deprecated
    public static pdb2.Person transform(pdb1.Person source) {
        if (source == null) {
            return null;
        }

        pdb2.Person target = Pdb2Factory.eINSTANCE.createPerson();

        // Attribute mappings
        target.setName(source.getFirstName() + ' ' + source.getLastName());
        target.setName(source.getFirstName() + ' ' + source.getLastName());
        target.setBirthday(source.getBirthday());
        target.setPlaceOfBirth(source.getPlaceOfBirth());
        target.setId(source.getId());
        target.setIncrementalID(source.getIncrementalID());

        // Reference mappings
        // Many-to-many: persons → persons
//        for (pdb1.Person srcItem : source.getPersons()) {
//            target.getPersons().add(transformPerson(srcItem));
//        }
//        // Single reference: database → database
//        if (source.getDatabase() != null) {
//            target.setDatabase(transformDatabase(source.getDatabase()));
//        }

        return target;
    }

    /**
     * Transforms a single Person object back.
     * @deprecated Use transformBack(Resource, ResourceSet) for full model transformation.
     */
    @Deprecated
    public static pdb1.Person transformBack(pdb2.Person target) {
        if (target == null) {
            return null;
        }

        pdb1.Person source = Pdb1Factory.eINSTANCE.createPerson();

        // Attribute mappings (backward)
        source.setFirstName(target.getName().split(" ")[0]);
        source.setLastName(target.getName().split(" ")[1]);
        source.setBirthday(target.getBirthday());
        source.setPlaceOfBirth(target.getPlaceOfBirth());
        source.setId(target.getId());
        source.setIncrementalID(target.getIncrementalID());

        // Reference mappings (backward)
        // Many-to-many (backward): persons → persons
//        for (Person tgtItem : target.getPersons()) {
//            source.getPersons().add(transformBackPerson(tgtItem));
//        }
//        // Single reference (backward): database → database
//        if (target.getDatabase() != null) {
//            source.setDatabase(transformBackDatabase(target.getDatabase()));
//        }

        return source;
    }

    // ════════════════════════════════════════════════════════════════════════
    // Helper Methods for Type-Specific Transformations
    // ════════════════════════════════════════════════════════════════════════

    /**
     * Transforms Person → Person
     */
    private static pdb2.Person transformPerson(pdb1.Person source) {
        if (source == null) {
            return null;
        }

        pdb2.Person target = Pdb2Factory.eINSTANCE.createPerson();

        // Root type - apply all attribute mappings
        target.setName(source.getFirstName() + ' ' + source.getLastName());
        target.setName(source.getFirstName() + ' ' + source.getLastName());
        target.setBirthday(source.getBirthday());
        target.setPlaceOfBirth(source.getPlaceOfBirth());
        target.setId(source.getId());
        target.setIncrementalID(source.getIncrementalID());

        return target;
    }

    /**
     * Transforms Person → Person (backward)
     */
    private static pdb1.Person transformBackPerson(pdb2.Person target) {
        if (target == null) {
            return null;
        }

        pdb1.Person source = Pdb1Factory.eINSTANCE.createPerson();

        // Root type - apply all backward attribute mappings
        source.setFirstName(target.getName().split(" ")[0]);
        source.setLastName(target.getName().split(" ")[1]);
        source.setBirthday(target.getBirthday());
        source.setPlaceOfBirth(target.getPlaceOfBirth());
        source.setId(target.getId());
        source.setIncrementalID(target.getIncrementalID());

        return source;
    }

    /**
     * Transforms Database → Database
     */
    private static pdb2.Database transformDatabase(pdb1.Database source) {
        if (source == null) {
            return null;
        }

        pdb2.Database target = Pdb2Factory.eINSTANCE.createDatabase();

        // Non-root type - add specific mappings if needed
        // TODO: Add attribute/reference mappings for Database
        target.setName(source.getName());

        return target;
    }

    /**
     * Transforms Database → Database (backward)
     */
    private static pdb1.Database transformBackDatabase(pdb2.Database target) {
        if (target == null) {
            return null;
        }

        pdb1.Database source = Pdb1Factory.eINSTANCE.createDatabase();

        // Non-root type - add specific mappings if needed
        // TODO: Add attribute/reference mappings for Database
        source.setName(target.getName());

        return source;
    }

}