package de.tbuchmann.bxagent.f2p;

// EMF imports for source and target packages
import Families.*;
import Persons.*;
import org.eclipse.emf.ecore.*;
import org.eclipse.emf.ecore.resource.*;
import org.eclipse.emf.ecore.util.EcoreUtil;
import java.util.*;

/**
 * Bidirectional EMF transformation: Families ↔ Persons
 * Generated by emt-agent.
 *
 * WARNING: Do not edit manually - will be overwritten on regeneration.
 */
public class Families2PersonsTransformation {

    // ════════════════════════════════════════════════════════════════════════
    // Transformation Options
    // ════════════════════════════════════════════════════════════════════════

    /**
     * Configuration options for non-deterministic transformation steps.
     * Includes both attribute-level options and structural backward-direction parameters.
     * Pass to transform() or transformBack() to control ambiguous mappings.
     */
    public record Options(
        boolean preferExistingFamily,  // Whether to reuse existing Family objects when transforming back from Persons to Families
        boolean preferParentOverChildRole
    ) {
        /** Default options. */
        public static Options defaults() {
            return new Options(
                true,
                true
            );
        }
    }

    // ════════════════════════════════════════════════════════════════════════
    // Public Entry Points - Resource-level Transformation
    // ════════════════════════════════════════════════════════════════════════

    /**
     * Transforms the contents of sourceResource into targetResource using default options.
     * Both resources must already exist and the root elements must be pre-created.
     *
     * @param sourceResource Source EMF resource (read)
     * @param targetResource Target EMF resource (written into, root elements must exist)
     */
    public static void transform(Resource sourceResource, Resource targetResource) {
        transform(sourceResource, targetResource, Options.defaults());
    }

    /**
     * Transforms the contents of sourceResource into targetResource.
     * Both resources must already exist and the root elements must be pre-created.
     * Uses two-phase transformation: (1) create contained objects, (2) resolve cross-references.
     *
     * @param sourceResource Source EMF resource (read)
     * @param targetResource Target EMF resource (written into, root elements must exist)
     * @param options Configuration options for non-deterministic mappings
     */
    public static void transform(Resource sourceResource, Resource targetResource, Options options) {
        if (sourceResource == null || targetResource == null) {
            return;
        }

        // Object mapping for cross-reference resolution
        Map<EObject, EObject> objectMap = new HashMap<>();
        Set<EObject> visited = new HashSet<>();

        // Pre-populate objectMap with existing root element pairs (by index)
        // and apply root-type attribute mappings
        List<EObject> sourceRoots = sourceResource.getContents();
        List<EObject> targetRoots = targetResource.getContents();
        for (int i = 0; i < Math.min(sourceRoots.size(), targetRoots.size()); i++) {
            Families.FamilyRegister source = (Families.FamilyRegister) sourceRoots.get(i);
            Persons.PersonRegister target = (Persons.PersonRegister) targetRoots.get(i);
            objectMap.put(source, target);
        }

        // Phase 1: Traverse containment hierarchy and create contained objects
        for (EObject sourceRoot : sourceRoots) {
            createAndMapObjects(sourceRoot, objectMap, visited, options);
        }

        // Phase 1b: Role-based type mappings (intermediate types without target counterparts)
        for (int i = 0; i < Math.min(sourceRoots.size(), targetRoots.size()); i++) {
            mapRoleBasedTypes(
                (Families.FamilyRegister) sourceRoots.get(i),
                (Persons.PersonRegister) targetRoots.get(i),
                objectMap
            );
        }

        // Phase 2: Resolve all cross-references
        resolveReferences(objectMap);
    }

    /**
     * Transforms the contents of targetResource back into sourceResource using default options.
     * Both resources must already exist and the root elements must be pre-created.
     *
     * @param targetResource Target EMF resource (read)
     * @param sourceResource Source EMF resource (written into, root elements must exist)
     */
    public static void transformBack(Resource targetResource, Resource sourceResource) {
        transformBack(targetResource, sourceResource, Options.defaults());
    }

    /**
     * Transforms the contents of targetResource back into sourceResource.
     * Both resources must already exist and the root elements must be pre-created.
     * Uses two-phase transformation: (1) create contained objects, (2) resolve cross-references.
     *
     * @param targetResource Target EMF resource (read)
     * @param sourceResource Source EMF resource (written into, root elements must exist)
     * @param options Configuration options for non-deterministic mappings
     */
    public static void transformBack(Resource targetResource, Resource sourceResource, Options options) {
        if (targetResource == null || sourceResource == null) {
            return;
        }

        // Object mapping for cross-reference resolution
        Map<EObject, EObject> objectMap = new HashMap<>();
        Set<EObject> visited = new HashSet<>();

        // Pre-populate objectMap with existing root element pairs (by index)
        // and apply root-type backward attribute mappings
        List<EObject> targetRoots = targetResource.getContents();
        List<EObject> sourceRoots = sourceResource.getContents();
        for (int i = 0; i < Math.min(targetRoots.size(), sourceRoots.size()); i++) {
            Persons.PersonRegister target = (Persons.PersonRegister) targetRoots.get(i);
            Families.FamilyRegister source = (Families.FamilyRegister) sourceRoots.get(i);
            objectMap.put(target, source);
        }

        // Phase 1: Traverse containment hierarchy and create contained objects
        for (EObject targetRoot : targetRoots) {
            createAndMapObjectsBack(targetRoot, objectMap, visited, options);
        }

        // Phase 1b: Role-based type mappings backward
        for (int i = 0; i < Math.min(targetRoots.size(), sourceRoots.size()); i++) {
            mapRoleBasedTypesBack(
                (Persons.PersonRegister) targetRoots.get(i),
                (Families.FamilyRegister) sourceRoots.get(i),
                options
            );
        }

        // Phase 2: Resolve all cross-references
        resolveReferencesBack(objectMap);
    }

    // ════════════════════════════════════════════════════════════════════════
    // Phase 1: Object Creation and Attribute Mapping (Forward)
    // ════════════════════════════════════════════════════════════════════════

    /**
     * Recursively creates target objects for source object tree (containments only).
     * Maps attributes and stores source→target mapping.
     * Pre-existing entries in objectMap (e.g. root elements) are traversed but not recreated.
     */
    private static EObject createAndMapObjects(EObject source, Map<EObject, EObject> objectMap, Set<EObject> visited, Options options) {
        if (source == null) {
            return null;
        }

        // Use visited set to prevent infinite loops (objectMap alone is not enough
        // since root elements are pre-seeded and must still be traversed)
        if (visited.contains(source)) {
            return objectMap.get(source);
        }
        visited.add(source);

        EObject target;
        if (objectMap.containsKey(source)) {
            // Pre-existing entry (e.g. root element) — use it, still traverse children
            target = objectMap.get(source);
        } else {
            target = null;

            // Handle FamilyRegister → PersonRegister
            if (source instanceof Families.FamilyRegister) {
                target = transformFamilyRegister((Families.FamilyRegister) source, options);
            } else
            // Handle FamilyMember → Person
            if (source instanceof Families.FamilyMember) {
                target = transformFamilyMember((Families.FamilyMember) source, options);
            }

            if (target != null) {
                objectMap.put(source, target);
            }
        }

        if (target != null) {

            // Recursively transform containment references
            // Containment: FamilyRegister.families → PersonRegister.persons
            if (source instanceof Families.FamilyRegister && target instanceof Persons.PersonRegister) {
                for (Families.Family child : ((Families.FamilyRegister) source).getFamilies()) {
                    EObject transformedChild = createAndMapObjects(child, objectMap, visited, options);
                    if (transformedChild instanceof Persons.Person) {
                        ((Persons.PersonRegister) target).getPersons().add((Persons.Person) transformedChild);
                    }
                }
            }
            // Containment: Family.father → Person.personsInverse
            if (source instanceof Families.Family && target instanceof Persons.Person) {
                Families.FamilyMember child = ((Families.Family) source).getFather();
                if (child != null) {
                    EObject transformedChild = createAndMapObjects(child, objectMap, visited, options);
                    if (transformedChild instanceof Persons.PersonRegister) {
                        ((Persons.Person) target).setPersonsInverse((Persons.PersonRegister) transformedChild);
                    }
                }
            }
            // Containment: Family.mother → Person.personsInverse
            if (source instanceof Families.Family && target instanceof Persons.Person) {
                Families.FamilyMember child = ((Families.Family) source).getMother();
                if (child != null) {
                    EObject transformedChild = createAndMapObjects(child, objectMap, visited, options);
                    if (transformedChild instanceof Persons.PersonRegister) {
                        ((Persons.Person) target).setPersonsInverse((Persons.PersonRegister) transformedChild);
                    }
                }
            }
            // Containment: Family.sons → Person.personsInverse
            if (source instanceof Families.Family && target instanceof Persons.Person) {
                for (Families.FamilyMember child : ((Families.Family) source).getSons()) {
                    EObject transformedChild = createAndMapObjects(child, objectMap, visited, options);
                    if (transformedChild instanceof Persons.PersonRegister) {
                        ((Persons.Person) target).setPersonsInverse((Persons.PersonRegister) transformedChild);
                    }
                }
            }
            // Containment: Family.daughters → Person.personsInverse
            if (source instanceof Families.Family && target instanceof Persons.Person) {
                for (Families.FamilyMember child : ((Families.Family) source).getDaughters()) {
                    EObject transformedChild = createAndMapObjects(child, objectMap, visited, options);
                    if (transformedChild instanceof Persons.PersonRegister) {
                        ((Persons.Person) target).setPersonsInverse((Persons.PersonRegister) transformedChild);
                    }
                }
            }
        }

        return target;
    }

    // ════════════════════════════════════════════════════════════════════════
    // Phase 2: Cross-Reference Resolution (Forward)
    // ════════════════════════════════════════════════════════════════════════

    /**
     * Resolves all cross-references (non-containment) using the object map.
     */
    private static void resolveReferences(Map<EObject, EObject> objectMap) {
        // No cross-references defined
    }

    // ════════════════════════════════════════════════════════════════════════
    // Phase 1: Object Creation and Attribute Mapping (Backward)
    // ════════════════════════════════════════════════════════════════════════

    /**
     * Recursively creates source objects for target object tree (containments only).
     * Maps attributes and stores target→source mapping.
     * Pre-existing entries in objectMap (e.g. root elements) are traversed but not recreated.
     */
    private static EObject createAndMapObjectsBack(EObject target, Map<EObject, EObject> objectMap, Set<EObject> visited, Options options) {
        if (target == null) {
            return null;
        }

        // Use visited set to prevent infinite loops (objectMap alone is not enough
        // since root elements are pre-seeded and must still be traversed)
        if (visited.contains(target)) {
            return objectMap.get(target);
        }
        visited.add(target);

        EObject source;
        if (objectMap.containsKey(target)) {
            // Pre-existing entry (e.g. root element) — use it, still traverse children
            source = objectMap.get(target);
        } else {
            source = null;

            // Handle PersonRegister → FamilyRegister
            if (target instanceof Persons.PersonRegister) {
                source = transformBackPersonRegister((Persons.PersonRegister) target, options);
            } else
            // Handle Person → FamilyMember
            if (target instanceof Persons.Person) {
                source = transformBackPerson((Persons.Person) target, options);
            }

            if (source != null) {
                objectMap.put(target, source);
            }
        }

        if (source != null) {

            // Recursively transform containment references
            // Containment (backward): PersonRegister.persons → FamilyRegister.families
            if (target instanceof Persons.PersonRegister && source instanceof Families.FamilyRegister) {
                for (Persons.Person child : ((Persons.PersonRegister) target).getPersons()) {
                    EObject transformedChild = createAndMapObjectsBack(child, objectMap, visited, options);
                    if (transformedChild instanceof Families.Family) {
                        ((Families.FamilyRegister) source).getFamilies().add((Families.Family) transformedChild);
                    }
                }
            }
        }

        return source;
    }

    // ════════════════════════════════════════════════════════════════════════
    // Phase 2: Cross-Reference Resolution (Backward)
    // ════════════════════════════════════════════════════════════════════════

    /**
     * Resolves all cross-references (non-containment) using the object map.
     */
    private static void resolveReferencesBack(Map<EObject, EObject> objectMap) {
        // Cross-reference (backward): Person.personsInverse → Family.father
        for (Map.Entry<EObject, EObject> entry : objectMap.entrySet()) {
            EObject target = entry.getKey();
            EObject source = entry.getValue();

            if (target instanceof Persons.Person && source instanceof Families.Family) {
                Persons.PersonRegister refTgt = ((Persons.Person) target).getPersonsInverse();
                if (refTgt != null) {
                    EObject refSrc = objectMap.get(refTgt);
                    if (refSrc instanceof Families.FamilyMember) {
                        ((Families.Family) source).setFather((Families.FamilyMember) refSrc);
                    }
                }
            }
        }

        // Cross-reference (backward): Person.personsInverse → Family.mother
        for (Map.Entry<EObject, EObject> entry : objectMap.entrySet()) {
            EObject target = entry.getKey();
            EObject source = entry.getValue();

            if (target instanceof Persons.Person && source instanceof Families.Family) {
                Persons.PersonRegister refTgt = ((Persons.Person) target).getPersonsInverse();
                if (refTgt != null) {
                    EObject refSrc = objectMap.get(refTgt);
                    if (refSrc instanceof Families.FamilyMember) {
                        ((Families.Family) source).setMother((Families.FamilyMember) refSrc);
                    }
                }
            }
        }

        // Cross-reference (backward): Person.personsInverse → Family.sons
        for (Map.Entry<EObject, EObject> entry : objectMap.entrySet()) {
            EObject target = entry.getKey();
            EObject source = entry.getValue();

            if (target instanceof Persons.Person && source instanceof Families.Family) {            	
                Persons.PersonRegister refTgt = ((Persons.Person) target).getPersonsInverse(); 
                EObject refSrc = objectMap.get(refTgt);
                if (refSrc instanceof Families.FamilyMember) {
                        ((Families.Family) source).getSons().add((Families.FamilyMember) refSrc);
                }
            }            
        }

        // Cross-reference (backward): Person.personsInverse → Family.daughters
        for (Map.Entry<EObject, EObject> entry : objectMap.entrySet()) {
            EObject target = entry.getKey();
            EObject source = entry.getValue();

            if (target instanceof Persons.Person && source instanceof Families.Family) {
                Persons.PersonRegister refTgt = ((Persons.Person) target).getPersonsInverse(); 
                EObject refSrc = objectMap.get(refTgt);
                if (refSrc instanceof Families.FamilyMember) {
                    ((Families.Family) source).getDaughters().add((Families.FamilyMember) refSrc);
                }                
            }
        }

    }

    // ════════════════════════════════════════════════════════════════════════
    // Single-Object Transformation Methods (kept for backwards compatibility)
    // ════════════════════════════════════════════════════════════════════════

    /**
     * Transforms a single FamilyRegister object.
     * @deprecated Use transform(Resource, Resource) for full model transformation.
     */
    @Deprecated
    public static Persons.PersonRegister transform(Families.FamilyRegister source) {
        return transformFamilyRegister(source, Options.defaults());
    }

    /**
     * Transforms a single PersonRegister object back.
     * @deprecated Use transformBack(Resource, Resource) for full model transformation.
     */
    @Deprecated
    public static Families.FamilyRegister transformBack(Persons.PersonRegister target) {
        return transformBackPersonRegister(target, Options.defaults());
    }

    // ════════════════════════════════════════════════════════════════════════
    // Helper Methods for Type-Specific Transformations
    // ════════════════════════════════════════════════════════════════════════

    // ════════════════════════════════════════════════════════════════════════
    // Role-Based Type Mapping Methods
    // ════════════════════════════════════════════════════════════════════════

    /**
     * Forward: maps source objects to target types based on their role in the intermediate container.
     * Iterates over intermediate objects, creates target objects per role, and adds them to objectMap.
     */
    private static void mapRoleBasedTypes(
            Families.FamilyRegister sourceRoot,
            Persons.PersonRegister targetRoot,
            Map<EObject, EObject> objectMap) {
        // FamilyMember → role-based target types via Family
        for (Families.Family family : sourceRoot.getFamilies()) {
            if (family.getFather() != null) {
                Families.FamilyMember member = family.getFather();
                Persons.Male obj = PersonsFactory.eINSTANCE.createMale();
                obj.setName(family.getName() + ", " + member.getName());
                targetRoot.getPersons().add(obj);
                objectMap.put(member, obj);
            }
            if (family.getMother() != null) {
                Families.FamilyMember member = family.getMother();
                Persons.Female obj = PersonsFactory.eINSTANCE.createFemale();
                obj.setName(family.getName() + ", " + member.getName());
                targetRoot.getPersons().add(obj);
                objectMap.put(member, obj);
            }
            for (Families.FamilyMember member : family.getSons()) {
                Persons.Male obj = PersonsFactory.eINSTANCE.createMale();
                obj.setName(family.getName() + ", " + member.getName());
                targetRoot.getPersons().add(obj);
                objectMap.put(member, obj);
            }
            for (Families.FamilyMember member : family.getDaughters()) {
                Persons.Female obj = PersonsFactory.eINSTANCE.createFemale();
                obj.setName(family.getName() + ", " + member.getName());
                targetRoot.getPersons().add(obj);
                objectMap.put(member, obj);
            }
        }
    }

    /**
     * Backward: maps target objects back to source type, assigns to role in intermediate container.
     * Creates intermediate objects as needed and assigns members to roles based on options.
     */
    private static void mapRoleBasedTypesBack(
            Persons.PersonRegister targetRoot,
            Families.FamilyRegister sourceRoot,
            Options options) {
        // Person → FamilyMember via Family
        Map<String, Families.Family> familyLookup = new HashMap<>();
        for (Persons.Person targetObj : targetRoot.getPersons()) {
            String intermediateKey = targetObj.getName().contains(",") ? targetObj.getName().substring(0, targetObj.getName().indexOf(',')) : targetObj.getName();
            String memberName = targetObj.getName().contains(",") ? targetObj.getName().substring(targetObj.getName().indexOf(',') + 1) : "";
            Families.Family family =
                    options.preferExistingFamily() ? familyLookup.getOrDefault(intermediateKey, null) : null;
            if (family == null) {
                family = FamiliesFactory.eINSTANCE.createFamily();
                family.setName(intermediateKey);
                sourceRoot.getFamilies().add(family);
                familyLookup.put(intermediateKey, family);
            }
            Families.FamilyMember member = FamiliesFactory.eINSTANCE.createFamilyMember();
            member.setName(memberName.trim());
            if (targetObj instanceof Persons.Male) {
                if (options.preferParentOverChildRole() && family.getFather() == null) {
                    family.setFather(member);
                } else {
                    family.getSons().add(member);
                }
            } else if (targetObj instanceof Persons.Female) {
                if (options.preferParentOverChildRole() && family.getMother() == null) {
                    family.setMother(member);
                } else {
                    family.getDaughters().add(member);
                }
            }
        }
    }

    /**
     * Transforms FamilyRegister → PersonRegister
     */
    private static Persons.PersonRegister transformFamilyRegister(Families.FamilyRegister source, Options options) {
        if (source == null) {
            return null;
        }

        Persons.PersonRegister target = PersonsFactory.eINSTANCE.createPersonRegister();

        return target;
    }

    /**
     * Transforms PersonRegister → FamilyRegister (backward)
     */
    private static Families.FamilyRegister transformBackPersonRegister(Persons.PersonRegister target, Options options) {
        if (target == null) {
            return null;
        }

        Families.FamilyRegister source = FamiliesFactory.eINSTANCE.createFamilyRegister();

        return source;
    }

    /**
     * Transforms FamilyMember → Person
     */
    private static Persons.Person transformFamilyMember(Families.FamilyMember source, Options options) {
        if (source == null) {
            return null;
        }
        
        Persons.Person target = null;
		// Role-based type mapping via Family
        if (source.eContainer() instanceof Families.Family) {
			Families.Family family = (Families.Family) source.eContainer();
			if (family.getFather() == source || family.getSons().contains(source)) {
				target = PersonsFactory.eINSTANCE.createMale();
			} else if (family.getMother() == source || family.getDaughters().contains(source)) {
				target = PersonsFactory.eINSTANCE.createFemale();
			} 
		} 

        target.setName(((Family)source.eContainer()).getName() + ", " + source.getName());
        return target;
    }

    /**
     * Transforms Person → FamilyMember (backward)
     */
    private static Families.FamilyMember transformBackPerson(Persons.Person target, Options options) {
        if (target == null) {
            return null;
        }

        Families.FamilyMember source = FamiliesFactory.eINSTANCE.createFamilyMember();

        //source.setName(target.getName().contains(", ") ? target.getName().substring(0, target.getName().indexOf(", ")) : target.getName());
        source.setName(target.getName().contains(", ") ? target.getName().substring(target.getName().indexOf(", ") + 1) : "");
        source.setName(source.getName().trim());
        return source;
    }

}
