package de.tbuchmann.bxagent.f2p;

// EMF imports for source and target packages
import Families.*;
import Persons.*;
import org.eclipse.emf.ecore.*;
import org.eclipse.emf.ecore.resource.*;
import org.eclipse.emf.ecore.util.EcoreUtil;
import java.util.*;

/**
 * Bidirectional EMF transformation: Families ↔ Persons
 * Generated by emt-agent.
 *
 * WARNING: Do not edit manually - will be overwritten on regeneration.
 */
public class Families2PersonsTransformation_first {
	// wir müssen die beiden Resourcen als Objektfeld speichern
	private Resource sourceResource;
	private Resource targetResource;

    // ════════════════════════════════════════════════════════════════════════
    // Transformation Options
    // ════════════════════════════════════════════════════════════════════════

    /**
     * Configuration options for non-deterministic transformation steps.
     * Pass to transform() or transformBack() to control ambiguous mappings.
     */
    public record Options(
        boolean preferExistingFamily,  // Whether to prefer existing family when matching in backward transformation
        boolean preferParentOverChildRole  // Whether to prefer parent role over child role when determining Male/Female in backward transformation
    ) {
        /** Default options. */
        public static Options defaults() {
            return new Options(
                true,
                true
            );
        }
    }
    
    public Families2PersonsTransformation_first(Resource sourceResource, Resource targetResource) {
		this.sourceResource = sourceResource;
		this.targetResource = targetResource;
	}

    // ════════════════════════════════════════════════════════════════════════
    // Public Entry Points - Resource-level Transformation
    // ════════════════════════════════════════════════════════════════════════

    /**
     * Transforms the contents of sourceResource into targetResource using default options.
     * Both resources must already exist and the root elements must be pre-created.
     *
     * @param sourceResource Source EMF resource (read)
     * @param targetResource Target EMF resource (written into, root elements must exist)
     */
    public void transform(/*Resource sourceResource, Resource targetResource*/) {
        transform(/*sourceResource, targetResource,*/ Options.defaults());
    }

    /**
     * Transforms the contents of sourceResource into targetResource.
     * Both resources must already exist and the root elements must be pre-created.
     * Uses two-phase transformation: (1) create contained objects, (2) resolve cross-references.
     *
     * @param sourceResource Source EMF resource (read)
     * @param targetResource Target EMF resource (written into, root elements must exist)
     * @param options Configuration options for non-deterministic mappings
     */
    public void transform(/*Resource sourceResource, Resource targetResource, */Options options) {
        if (sourceResource == null || targetResource == null) {
            return;
        }

        // Object mapping for cross-reference resolution
        Map<EObject, EObject> objectMap = new HashMap<>();
        Set<EObject> visited = new HashSet<>();

        // Pre-populate objectMap with existing root element pairs (by index)
        // and apply root-type attribute mappings
        List<EObject> sourceRoots = sourceResource.getContents();
        List<EObject> targetRoots = targetResource.getContents();
        for (int i = 0; i < Math.min(sourceRoots.size(), targetRoots.size()); i++) {
            Families.FamilyRegister source = (Families.FamilyRegister) sourceRoots.get(i);
            Persons.PersonRegister target = (Persons.PersonRegister) targetRoots.get(i);            
            objectMap.put(source, target);
        }

        // Phase 1: Traverse containment hierarchy and create contained objects
        // Family does not have a correspnonding type in Persons, daher wird hier nichts transformiert,
        // sondern es wird über die Familien gelaufen und die FamilyMember transformiert, welche dann in die PersonRegister eingehängt werden
        for (Family family : ((FamilyRegister)sourceRoots.get(0)).getFamilies()) {
        	List<FamilyMember> members = collectAllMembers(family);
        	for (FamilyMember member : members) {
        		((PersonRegister)targetRoots.get(0)).getPersons().add((Person) createAndMapObjects(member, objectMap, visited, options));
        	}
        }

        // Phase 2: Resolve all cross-references
        resolveReferences(objectMap);
    }

    /**
     * Transforms the contents of targetResource back into sourceResource using default options.
     * Both resources must already exist and the root elements must be pre-created.
     *
     * @param targetResource Target EMF resource (read)
     * @param sourceResource Source EMF resource (written into, root elements must exist)
     */
    public void transformBack(/*Resource targetResource, Resource sourceResource*/) {
        transformBack(/*targetResource, sourceResource,*/ Options.defaults());
    }

    /**
     * Transforms the contents of targetResource back into sourceResource.
     * Both resources must already exist and the root elements must be pre-created.
     * Uses two-phase transformation: (1) create contained objects, (2) resolve cross-references.
     *
     * @param targetResource Target EMF resource (read)
     * @param sourceResource Source EMF resource (written into, root elements must exist)
     * @param options Configuration options for non-deterministic mappings
     */
    public void transformBack(/*Resource targetResource, Resource sourceResource,*/ Options options) {
        if (targetResource == null || sourceResource == null) {
            return;
        }

        // Object mapping for cross-reference resolution
        Map<EObject, EObject> objectMap = new HashMap<>();
        Set<EObject> visited = new HashSet<>();

        // Pre-populate objectMap with existing root element pairs (by index)
        // and apply root-type backward attribute mappings
        List<EObject> targetRoots = targetResource.getContents();
        List<EObject> sourceRoots = sourceResource.getContents();
        for (int i = 0; i < Math.min(targetRoots.size(), sourceRoots.size()); i++) {
            Persons.PersonRegister target = (Persons.PersonRegister) targetRoots.get(i);
            Families.FamilyRegister source = (Families.FamilyRegister) sourceRoots.get(i);            
            objectMap.put(target, source);
        }

        // Phase 1: Traverse containment hierarchy and create contained objects
        for (EObject targetRoot : targetRoots) {
            createAndMapObjectsBack(targetRoot, objectMap, visited, options);
        }

        // Phase 2: Resolve all cross-references
        resolveReferencesBack(objectMap);
    }

    // ════════════════════════════════════════════════════════════════════════
    // Phase 1: Object Creation and Attribute Mapping (Forward)
    // ════════════════════════════════════════════════════════════════════════

    /**
     * Recursively creates target objects for source object tree (containments only).
     * Maps attributes and stores source→target mapping.
     * Pre-existing entries in objectMap (e.g. root elements) are traversed but not recreated.
     */
    private EObject createAndMapObjects(EObject source, Map<EObject, EObject> objectMap, Set<EObject> visited, Options options) {
        if (source == null) {
            return null;
        }

        // Use visited set to prevent infinite loops (objectMap alone is not enough
        // since root elements are pre-seeded and must still be traversed)
        if (visited.contains(source)) {
            return objectMap.get(source);
        }
        visited.add(source);

        EObject target;
        if (objectMap.containsKey(source)) {
            // Pre-existing entry (e.g. root element) — use it, still traverse children
            target = objectMap.get(source);
        } else {
            target = null;
            
            // Handle FamilyMember → Person
            if (source instanceof Families.FamilyMember) {
                target = transformFamilyMember((Families.FamilyMember) source, options);
            } 

            if (target != null) {
                objectMap.put(source, target);
            }
        }

        if (target != null) {

            // Recursively transform containment references
            // No containment references defined
        }      

        return target;
    }

    // ════════════════════════════════════════════════════════════════════════
    // Phase 2: Cross-Reference Resolution (Forward)
    // ════════════════════════════════════════════════════════════════════════

    /**
     * Resolves all cross-references (non-containment) using the object map.
     */
    private void resolveReferences(Map<EObject, EObject> objectMap) {
        // No cross-references defined
    }

    // ════════════════════════════════════════════════════════════════════════
    // Phase 1: Object Creation and Attribute Mapping (Backward)
    // ════════════════════════════════════════════════════════════════════════

    /**
     * Recursively creates source objects for target object tree (containments only).
     * Maps attributes and stores target→source mapping.
     * Pre-existing entries in objectMap (e.g. root elements) are traversed but not recreated.
     */
    private EObject createAndMapObjectsBack(EObject target, Map<EObject, EObject> objectMap, Set<EObject> visited, Options options) {
        if (target == null) {
            return null;
        }

        // Use visited set to prevent infinite loops (objectMap alone is not enough
        // since root elements are pre-seeded and must still be traversed)
        if (visited.contains(target)) {
            return objectMap.get(target);
        }
        visited.add(target);

        EObject source;
        if (objectMap.containsKey(target)) {
            // Pre-existing entry (e.g. root element) — use it, still traverse children
            source = objectMap.get(target);
        } else {
            source = null;

            // Handle Person → FamilyMember
            if (target instanceof Persons.Person) {
                source = transformBackPerson((Persons.Person) target, options);
            } else
            // Handle Person → Family
            if (target instanceof Persons.Person) {
                source = transformBackPerson((Persons.Person) target, options);
            }

            if (source != null) {
                objectMap.put(target, source);
            }
        }

        if (source != null) {

            // Recursively transform containment references
            // No containment references defined
        }

        return source;
    }

    // ════════════════════════════════════════════════════════════════════════
    // Phase 2: Cross-Reference Resolution (Backward)
    // ════════════════════════════════════════════════════════════════════════

    /**
     * Resolves all cross-references (non-containment) using the object map.
     */
    private void resolveReferencesBack(Map<EObject, EObject> objectMap) {
        // Cross-reference (backward): Male.personsInverse → FamilyMember.fatherInverse
        for (Map.Entry<EObject, EObject> entry : objectMap.entrySet()) {
            EObject target = entry.getKey();
            EObject source = entry.getValue();

            if (target instanceof Persons.Male && source instanceof Families.FamilyMember) {
                Persons.PersonRegister refTgt = ((Persons.Male) target).getPersonsInverse();
                if (refTgt != null) {
                    EObject refSrc = objectMap.get(refTgt);
                    if (refSrc instanceof Families.Family) {
                        ((Families.FamilyMember) source).setFatherInverse((Families.Family) refSrc);
                    }
                }
            }
        }

        // Cross-reference (backward): Female.personsInverse → FamilyMember.motherInverse
        for (Map.Entry<EObject, EObject> entry : objectMap.entrySet()) {
            EObject target = entry.getKey();
            EObject source = entry.getValue();

            if (target instanceof Persons.Female && source instanceof Families.FamilyMember) {
                Persons.PersonRegister refTgt = ((Persons.Female) target).getPersonsInverse();
                if (refTgt != null) {
                    EObject refSrc = objectMap.get(refTgt);
                    if (refSrc instanceof Families.Family) {
                        ((Families.FamilyMember) source).setMotherInverse((Families.Family) refSrc);
                    }
                }
            }
        }

        // Cross-reference (backward): Male.personsInverse → FamilyMember.sonsInverse
        for (Map.Entry<EObject, EObject> entry : objectMap.entrySet()) {
            EObject target = entry.getKey();
            EObject source = entry.getValue();

            if (target instanceof Persons.Male && source instanceof Families.FamilyMember) {
                Persons.PersonRegister refTgt = ((Persons.Male) target).getPersonsInverse();
                if (refTgt != null) {
                    EObject refSrc = objectMap.get(refTgt);
                    if (refSrc instanceof Families.Family) {
                        ((Families.FamilyMember) source).setSonsInverse((Families.Family) refSrc);
                    }
                }
            }
        }

        // Cross-reference (backward): Female.personsInverse → FamilyMember.daughtersInverse
        for (Map.Entry<EObject, EObject> entry : objectMap.entrySet()) {
            EObject target = entry.getKey();
            EObject source = entry.getValue();

            if (target instanceof Persons.Female && source instanceof Families.FamilyMember) {
                Persons.PersonRegister refTgt = ((Persons.Female) target).getPersonsInverse();
                if (refTgt != null) {
                    EObject refSrc = objectMap.get(refTgt);
                    if (refSrc instanceof Families.Family) {
                        ((Families.FamilyMember) source).setDaughtersInverse((Families.Family) refSrc);
                    }
                }
            }
        }

    }

    // ════════════════════════════════════════════════════════════════════════
    // Single-Object Transformation Methods (kept for backwards compatibility)
    // ════════════════════════════════════════════════════════════════════════

    /**
     * Transforms a single FamilyMember object.
     * @deprecated Use transform(Resource, Resource) for full model transformation.
     */
    @Deprecated
    public Persons.Person transform(Families.FamilyMember source) {
        return transformFamilyMember(source, Options.defaults());
    }

    /**
     * Transforms a single Person object back.
     * @deprecated Use transformBack(Resource, Resource) for full model transformation.
     */
    @Deprecated
    public Families.FamilyMember transformBack(Persons.Person target) {
        return transformBackPerson(target, Options.defaults());
    }

    // ════════════════════════════════════════════════════════════════════════
    // Helper Methods for Type-Specific Transformations
    // ════════════════════════════════════════════════════════════════════════

    /**
     * Transforms FamilyMember → Person
     */
    private Persons.Person transformFamilyMember(Families.FamilyMember source, Options options) {
        if (source == null) {
            return null;
        }
        
        Persons.Person target;
        // hier anhand der Rollenpräferenz entscheiden, ob Person Male oder Female
        if (source.getFatherInverse() != null || source.getSonsInverse() != null)        
        	target = PersonsFactory.eINSTANCE.createMale();
        else
        	target = PersonsFactory.eINSTANCE.createFemale();

        target.setName(((Family)source.eContainer()).getName() + ", " + source.getName());
        return target;
    }

    /**
     * Transforms Person → FamilyMember (backward)
     */
    private Families.FamilyMember transformBackPerson(Persons.Person target, Options options) {
        if (target == null) {
            return null;
        }

        // find Family
        String familyName = target.getName().split(",")[0].trim();
        Family family = null;
        FamilyRegister famRegister = (FamilyRegister) sourceResource.getContents().get(0);
        if (options.preferExistingFamily()) {
        	// find familyregister        	
        	for (Family f : famRegister.getFamilies()) {
				if (f.getName().equals(familyName)) {
					family = f;
					break;
				}
			}
        }
        if (family == null) {
			// create new family
			family = FamiliesFactory.eINSTANCE.createFamily();
			family.setName(familyName);
			famRegister.getFamilies().add(family);
		}

        Families.FamilyMember source = FamiliesFactory.eINSTANCE.createFamilyMember();
        if (options.preferParentOverChildRole()) {
			// hier anhand der Rollenpräferenz entscheiden, ob Person
			// Vater/Mutter oder Sohn/Tochter wird	
			if (target instanceof Persons.Male) {
				family.setFather(source);
			} else {
				family.setMother(source);
			}
        } else {
        	if (target instanceof Persons.Male) {
				family.getSons().add(source);
			} else {
				family.getDaughters().add(source);
			}
        }

        source.setName(target.getName());
        source.setName(target.getName());
        return source;
    }

//    /**
//     * Transforms Family → Person
//     */
//    private static Persons.Person transformFamily(Families.Family source, Options options) {
//        if (source == null) {
//            return null;
//        }
//
//        Persons.Person target = PersonsFactory.eINSTANCE.createPerson();
//
//        target.setName(source.getName());
//        return target;
//    }

//    /**
//     * Transforms Person → Family (backward)
//     */
//    private static Families.Family transformBackPerson(Persons.Person target, Options options) {
//        if (target == null) {
//            return null;
//        }
//
//        Families.Family source = FamiliesFactory.eINSTANCE.createFamily();
//
//        source.setName(target.getName());
//        source.setName(target.getName());
//        return source;
//    }
    
    private static List<FamilyMember> collectAllMembers(Family family) {
		List<FamilyMember> members = new ArrayList<>();
		if (family.getFather() != null)
			members.add(family.getFather());
		if (family.getMother() != null)
			members.add(family.getMother());
		members.addAll(family.getSons());
		members.addAll(family.getDaughters());
		
		return members;
	}

}
